import {useEffect,useRef,useState,type FormEvent} from 'react';
import {toast} from 'sonner';
import {MessageCircle,Send,X,Printer} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import BrandLogo from './brand-logo';
import {PrintLoader} from './loading';
export function requestReceipt(record:any,student:string){window.dispatchEvent(new CustomEvent('eduka-receipt',{detail:{record,student}}))}
export function requestPrint(){window.dispatchEvent(new Event('eduka-print'))}
export default function Experience({userName,centerName}:{userName:string;centerName:string}){
 const [open,setOpen]=useState(false),[message,setMessage]=useState(''),[phone,setPhone]=useState(''),[sending,setSending]=useState(false),[error,setError]=useState(''),[messages,setMessages]=useState<{text:string;own:boolean}[]>([]),[receipt,setReceipt]=useState<any>(null),[printing,setPrinting]=useState(false);
 const end=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null),lock=useRef(false);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest'})},[messages,open]);
 async function print(){if(lock.current)return;lock.current=true;setPrinting(true);try{await Promise.all([document.fonts.ready,new Promise(resolve=>setTimeout(resolve,650)),...Array.from(document.images).map(img=>img.decode().catch(()=>{}))]);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));window.print()}catch{toast.error('Chop etish oynasi ochilmadi. Qayta urinib ko‘ring.')}finally{lock.current=false;setPrinting(false)}}
 useEffect(()=>{const receiptEvent=(e:Event)=>setReceipt((e as CustomEvent).detail);const printEvent=()=>{setReceipt(null);void print()};const chatEvent=()=>setOpen(true);window.addEventListener('eduka-receipt',receiptEvent);window.addEventListener('eduka-print',printEvent);window.addEventListener('eduka-chat',chatEvent);return()=>{window.removeEventListener('eduka-receipt',receiptEvent);window.removeEventListener('eduka-print',printEvent);window.removeEventListener('eduka-chat',chatEvent)}},[]);
 useEffect(()=>{document.body.classList.toggle('eduka-receipt-mode',!!receipt);return()=>document.body.classList.remove('eduka-receipt-mode')},[receipt]);
 async function send(e:FormEvent){e.preventDefault();if(sending||!message.trim())return;setSending(true);setError('');const text=message.trim();try{const r=await fetch('/api/support-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:userName,phone,question:location.hostname+' · '+centerName,message:text})});const data=await r.json();if(!r.ok||!data.ok)throw Error('Xabar yuborilmadi. Qayta urinib ko‘ring.');setMessages(prev=>[...prev,{text,own:true},{text:'Murojaatingiz qabul qilindi. Javob uchun ko‘rsatilgan telefon raqamingiz orqali bog‘lanamiz.',own:false}]);setMessage('')}catch(e:any){setError(e.message||'Aloqa uzildi. Qayta urinib ko‘ring.')}finally{setSending(false)}}
 function close(){setOpen(false);trigger.current?.focus()}
 return <>{printing&&<PrintLoader/>}<button ref={trigger} className="eduka-chat-trigger" aria-label={open?'Yordam chatini yopish':'EDUKA yordam chatini ochish'} aria-expanded={open} aria-controls="eduka-support" onClick={()=>setOpen(!open)}>{open?<X/>:<MessageCircle/>}</button>{open&&<section id="eduka-support" className="eduka-chat" role="dialog" aria-label="EDUKA yordam" onKeyDown={e=>{if(e.key==='Escape')close()}}><header><div><strong>EDUKA yordam</strong><small>Qo‘llab-quvvatlash xizmati</small></div><button aria-label="Chatni yopish" onClick={close}><X size={18}/></button></header><div className="eduka-chat-messages" role="log" aria-live="polite"><p>Assalomu alaykum! Savolingizni yozing, siz bilan bog‘lanamiz.</p>{messages.map((m,i)=><p key={i} className={m.own?'own':''}>{m.text}</p>)}<div ref={end}/></div><form onSubmit={send}><label htmlFor="support-phone">Bog‘lanish uchun telefon</label><input id="support-phone" type="tel" autoComplete="tel" placeholder="+998 90 123 45 67" required maxLength={30} value={phone} onChange={e=>setPhone(e.target.value)} disabled={sending}/><div className="eduka-chat-compose"><textarea aria-label="Xabaringiz" autoFocus placeholder="Savolingizni yozing…" maxLength={3000} required value={message} onChange={e=>setMessage(e.target.value)} disabled={sending}/><button type="submit" disabled={sending||!message.trim()} aria-label="Xabarni yuborish"><Send size={18}/></button></div>{sending&&<small role="status">Yuborilmoqda…</small>}{error&&<small role="alert">{error}</small>}</form></section>}
 <Dialog open={!!receipt} onOpenChange={v=>!v&&setReceipt(null)}><DialogContent className="eduka-receipt-dialog"><DialogHeader><DialogTitle>To‘lov cheki</DialogTitle><DialogDescription>Saqlangan to‘lov ma’lumotlari</DialogDescription></DialogHeader>{receipt&&<article className="eduka-receipt"><BrandLogo/><h2>{centerName}</h2><p>To‘lov tasdig‘i</p><dl>{[['Chek raqami',receipt.record.id],['Sana',receipt.record.data.date],['O‘quvchi',receipt.student||'—'],['Summa',Number(receipt.record.data.amount).toLocaleString('uz-UZ')+' so‘m'],['To‘lov turi',receipt.record.data.paymentMethod||'—'],['Chop etuvchi',userName]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><small>Ichki to‘lov tasdig‘i. Fiskal chek emas.</small></article>}<button className="login-submit" disabled={printing} onClick={print}><Printer size={16}/> Chop etish / PDF</button></DialogContent></Dialog></>
}
