import {useEffect,useRef,useState,type FormEvent} from 'react';
import {toast} from 'sonner';
import {MessageCircle,Send,X,Printer,Download} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import BrandLogo from './brand-logo';
import {PrintLoader} from './loading';
export function requestReceipt(record:any,student:string){window.dispatchEvent(new CustomEvent('eduka-receipt',{detail:{record,student}}))}
export default function Experience({userName,centerName,settings={}}:{userName:string;centerName:string;settings?:Record<string,any>}){
 const [open,setOpen]=useState(false),[message,setMessage]=useState(''),[sending,setSending]=useState(false),[error,setError]=useState(''),[messages,setMessages]=useState<{text:string;own:boolean}[]>([]),[receipt,setReceipt]=useState<any>(null),[printing,setPrinting]=useState(false),[unread,setUnread]=useState(0);
 const lastSeen=useRef(0),receiptRequest=useRef(0);
 const [receiptLoading,setReceiptLoading]=useState(false),[receiptError,setReceiptError]=useState('');
 async function loadReceipt(id:string){const request=++receiptRequest.current;setReceipt({record:{id,data:{}}});setReceiptLoading(true);setReceiptError('');try{const r=await fetch('/api/crm/receipts/'+encodeURIComponent(id));const d=await r.json();if(!r.ok)throw Error(d.error||'Chek yuklanmadi');if(request===receiptRequest.current)setReceipt(d)}catch(e:any){if(request===receiptRequest.current)setReceiptError(e.message)}finally{if(request===receiptRequest.current)setReceiptLoading(false)}}
 function downloadReceipt(){const article=document.querySelector('.eduka-receipt');if(!article)return;const html='<!doctype html><html lang="uz"><meta charset="utf-8"><title>EDUKA — ichki chek</title><style>body{font:16px Arial;margin:40px auto;max-width:520px;padding:20px}dl>div{display:flex;justify-content:space-between;gap:20px;border-bottom:1px solid #ddd;padding:10px}dd{margin:0;overflow-wrap:anywhere}img{max-width:160px}small{color:#667085}</style>'+article.outerHTML+'</html>';const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='EDUKA-chek-'+receipt.record.id+'.html';a.click();URL.revokeObjectURL(url)}
 const end=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null),lock=useRef(false);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest'})},[messages,open]);
 async function print(){if(lock.current)return;lock.current=true;setPrinting(true);try{await Promise.all([document.fonts.ready,new Promise(resolve=>setTimeout(resolve,650)),...Array.from(document.images).map(img=>img.decode().catch(()=>{}))]);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));window.print()}catch{toast.error('Chop etish oynasi ochilmadi. Qayta urinib ko‘ring.')}finally{lock.current=false;setPrinting(false)}}
 useEffect(()=>{const receiptEvent=(e:Event)=>void loadReceipt((e as CustomEvent).detail.record.id);const chatEvent=()=>setOpen(true);window.addEventListener('eduka-receipt',receiptEvent);window.addEventListener('eduka-chat',chatEvent);return()=>{window.removeEventListener('eduka-receipt',receiptEvent);window.removeEventListener('eduka-chat',chatEvent)}},[]);
 useEffect(()=>{document.body.classList.toggle('eduka-receipt-mode',!!receipt);return()=>document.body.classList.remove('eduka-receipt-mode')},[receipt]);
 async function loadMessages(){try{const r=await fetch('/api/crm/support');if(!r.ok)throw Error('Chatni yuklab bo‘lmadi');const d=await r.json();if(open){lastSeen.current=Date.now();setUnread(0)}else setUnread(d.messages.filter((m:any)=>m.sender==='operator'&&Date.parse(m.created_at)>lastSeen.current).length);setMessages(d.messages.map((m:any)=>({text:m.body,own:m.sender==='user'})))}catch(e:any){setError(e.message)}}
 useEffect(()=>{void loadMessages();const timer=setInterval(()=>{if(!document.hidden)void loadMessages()},10000);return()=>clearInterval(timer)},[open]);
 async function send(e:FormEvent){e.preventDefault();if(sending||!message.trim())return;setSending(true);setError('');try{const r=await fetch('/api/crm/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body:message.trim()})});const d=await r.json();if(!r.ok)throw Error(d.error||'Xabar yuborilmadi');setMessage('');await loadMessages()}catch(e:any){setError(e.message)}finally{setSending(false)}}

 function close(){setOpen(false);trigger.current?.focus()}
 return <>{printing&&<PrintLoader/>}<button ref={trigger} className="eduka-chat-trigger" aria-label={open?'Yordam chatini yopish':'EDUKA yordam chatini ochish'} aria-expanded={open} aria-controls="eduka-support" onClick={()=>setOpen(!open)}>{open?<X/>:<MessageCircle/>}{unread>0&&!open&&<span className="eduka-chat-unread" aria-label="O‘qilmagan javoblar">{unread}</span>}</button>{open&&<section id="eduka-support" className="eduka-chat" role="dialog" aria-label="EDUKA yordam" onKeyDown={e=>{if(e.key==='Escape')close()}}><header><div><strong>EDUKA yordam</strong><small>Qo‘llab-quvvatlash xizmati</small></div><button aria-label="Chatni yopish" onClick={close}><X size={18}/></button></header><div className="eduka-chat-messages" role="log" aria-live="polite"><p>Assalomu alaykum! Savolingizni yozing. Operator javobi shu oynada paydo bo‘ladi.</p>{messages.map((m,i)=><p key={i} className={m.own?'own':''}>{m.text}</p>)}<div ref={end}/></div><form onSubmit={send}><div className="eduka-chat-compose"><textarea aria-label="Xabaringiz" autoFocus placeholder="Savolingizni yozing…" maxLength={3000} required value={message} onChange={e=>setMessage(e.target.value)} disabled={sending}/><button type="submit" disabled={sending||!message.trim()} aria-label="Xabarni yuborish"><Send size={18}/></button></div>{sending&&<small role="status">Yuborilmoqda…</small>}{error&&<small role="alert">{error}</small>}</form></section>}
 <Dialog open={!!receipt} onOpenChange={v=>!v&&setReceipt(null)}><DialogContent className="eduka-receipt-dialog"><DialogHeader><DialogTitle>To‘lov cheki</DialogTitle><DialogDescription>Saqlangan to‘lov ma’lumotlari</DialogDescription></DialogHeader>{receiptLoading&&<p role="status">Chek yuklanmoqda…</p>}{receiptError&&<p role="alert">{receiptError}</p>}{receipt&&!receiptLoading&&!receiptError&&<article className="eduka-receipt" style={{fontSize:Number(settings.receiptFontSize)||14}}>{settings.centerLogo?<img src={settings.centerLogo} alt="Markaz logosi" style={{maxWidth:160,maxHeight:70,margin:'0 auto'}}/>:<BrandLogo/>}<h2>{receipt.centerName||centerName}</h2><p>{settings.centerPhone}</p><p>{settings.centerAddress}</p><p>{receipt.record.deleted?'BEKOR QILINGAN':receipt.record.data.direction==='Chiqim'?'Qaytarish / chiqim tasdig‘i':settings.receiptTitle||'To‘lov tasdig‘i'}</p><dl>{[['Chek raqami',receipt.record.id],['Sana',receipt.record.data.date],['O‘quvchi',receipt.student||'—'],['Summa',Number(receipt.record.data.amount).toLocaleString('uz-UZ')+' so‘m'],['To‘lov turi',receipt.record.data.paymentMethod||'—'],['Guruh',receipt.group],['Kassa',receipt.cash],['Qabul qilgan kassir',receipt.cashier],['Versiya',String(receipt.record.version)]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p>{settings.receiptFooter}</p><small>Ichki to‘lov tasdig‘i. Fiskal chek emas.</small></article>}<button className="login-submit" disabled={printing||receiptLoading||!!receiptError} onClick={print}><Printer size={16}/> Chop etish / PDF</button><button className="login-submit" disabled={receiptLoading||!!receiptError} onClick={downloadReceipt}><Download size={16}/>Chekni yuklab olish</button></DialogContent></Dialog></>
}
