import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {exportRows} from '@/lib/domain';
const money=(v:number)=>Number(v||0).toLocaleString('uz-UZ');
export default function FinanceSummary({revision,branch}:{revision:unknown;branch:string}){
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const c=new AbortController();setBusy(true);setError('');setData(null);fetch('/api/crm/finance-summary?'+new URLSearchParams({from,to}),{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!c.signal.aborted)setBusy(false)});return()=>c.abort()},[from,to,revision]);
 return <section className="panel" aria-label="Kassa va balans nazorati"><h3>Kassa va balans nazorati — barcha filiallar</h3><div className="profile-actions"><label>Boshlanish <input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Tugash <input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><Button variant="outline" disabled={!data||busy} onClick={()=>exportRows('Kassalar',['Kassa','Kirim','Qaytarish','Xarajat','Sof oqim'],data.cash.map((c:any)=>[c.name,c.income,c.refunds,c.expenses,c.net]))}>CSV yuklash</Button></div>{branch!=='all'&&<p className="form-note">Ushbu nazorat markaz bo‘yicha jami; pastdagi jadval tanlangan filial bo‘yicha.</p>}{busy&&<p role="status">Hisoblanmoqda…</p>}{error&&<p role="alert">{error}</p>}{data&&<><div className="mini-stats">{[['Kirim',data.totals.income],['Qaytarilgan',data.totals.refunds],['Xarajat',data.totals.expenses],['Sof pul oqimi',data.totals.net]].map(([k,v])=><div key={k}><span>{k}</span><strong>{money(v)} UZS</strong></div>)}</div><div className="table-panel"><table><thead><tr>{['Kassa','Kirim','Qaytarish','Xarajat','Sof oqim'].map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{data.cash.map((c:any)=><tr key={c.id}><td>{c.name}</td>{[c.income,c.refunds,c.expenses,c.net].map((v,i)=><td key={i}>{money(v)}</td>)}</tr>)}</tbody></table>{!data.cash.length&&<p>Bu davrda operatsiyalar yo‘q.</p>}</div><p>Joriy o‘quvchi qarzi: {money(data.studentDebt)} UZS · Oldindan to‘langan qoldiq: {money(data.studentCredit)} UZS</p><p role="status">{data.balanceMismatches?`Balansi mos kelmagan o‘quvchilar: ${data.balanceMismatches}`:'O‘quvchilar balansi bazadagi hisob-kitob bilan mos.'}</p><p className="form-note">Kassa summalari tanlangan davrdagi operatsiyalar bo‘yicha. O‘quvchi qarzi va qoldig‘i barcha sanalar bo‘yicha joriy holat. Sof oqim kassa boshlang‘ich qoldig‘ini hisobga olmaydi.</p></>}</section>
}
