import {useEffect,useState} from 'react';
import {settingsSections,settingDefaults,activeSettingKeys} from '@/lib/settings';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Switch} from '@/components/ui/switch';
import {toast} from 'sonner';
export default function SettingsPanel({page,records,save,centerName}:{page:any;records:any[];save:any;centerName:string}){
 const section=page.path.split('/').pop(),groups=settingsSections[section]||{};
 const existing=records.find(r=>r.entity==='settings'&&r.data.section===section);
 const baseline={...settingDefaults[section],...(section==='system'?{centerName}:{}),...existing?.data,section};
 const [data,setData]=useState<any>(baseline),[tab,setTab]=useState(Object.keys(groups)[0]||''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setData(baseline);setError('')},[section,existing?.id,existing?.version]);
 useEffect(()=>{setTab(Object.keys(groups)[0]||'')},[section]);
 const changed=JSON.stringify(data)!==JSON.stringify(baseline);
 useEffect(()=>{if(!changed)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};const navigate=(e:MouseEvent)=>{const a=(e.target as HTMLElement).closest('a[href]');if(a&&a.getAttribute('href')!==window.location.pathname&&!confirm('Saqlanmagan o‘zgarishlar bor. Sahifadan chiqasizmi?')){e.preventDefault();e.stopPropagation()}};window.addEventListener('beforeunload',warn);document.addEventListener('click',navigate,true);return()=>{window.removeEventListener('beforeunload',warn);document.removeEventListener('click',navigate,true)}},[changed]);
 async function upload(file?:File){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024){setError('Logo JPG, PNG yoki WebP, 2 MB gacha bo‘lsin');return}setUploading(true);setError('');try{const form=new FormData();form.append('file',file);const r=await fetch('/api/crm/files',{method:'POST',body:form});const d=await r.json();if(!r.ok)throw Error(d.error);setData((v:any)=>({...v,centerLogo:d.url}))}catch(e:any){setError(e.message)}finally{setUploading(false)}}
 return <div className="settings-layout"><aside className="settings-nav">{Object.keys(groups).map(title=><button key={title} className={tab===title?'active':''} onClick={()=>setTab(title)}>{title}</button>)}<a href="/branches">Filiallarni boshqarish</a><a href="/finance/payment-type">Tranzaksiya turlari</a><a href="/course/contracts">Shartnoma shablonlari</a></aside><form className="panel settings-panel" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await save('settings',data,existing);toast.success('Sozlamalar saqlandi')}catch(e:any){setError(e.message)}finally{setBusy(false)}}}><div className="section-heading"><h2>{tab}</h2><Button type="submit" disabled={busy||uploading||(!changed&&!!existing)}>{busy?'Saqlanmoqda…':'Saqlash'}</Button></div>{(groups[tab]||[]).map(f=>{const enabled=activeSettingKeys.includes(f.key);return <div className="setting-row" key={f.key}><label htmlFor={'setting-'+f.key}>{f.label}{!enabled&&<small style={{display:'block',color:'#667085'}}>Hali ulanmagan</small>}</label>{f.type==='file'?<div>{data.centerLogo&&<img src={data.centerLogo} alt="Markaz logosi" style={{height:56,maxWidth:180,objectFit:'contain'}}/>}<input aria-label="Logo yuklash" type="file" accept="image/png,image/jpeg,image/webp" disabled={busy||uploading} onChange={e=>upload(e.target.files?.[0])}/>{data.centerLogo&&<Button type="button" variant="outline" onClick={()=>setData({...data,centerLogo:''})}>Logoni olib tashlash</Button>}{uploading&&<small>Yuklanmoqda…</small>}</div>:f.type==='switch'?<Switch id={'setting-'+f.key} disabled={!enabled||busy} checked={enabled&&!!data[f.key]} onCheckedChange={v=>setData({...data,[f.key]:v})}/>:f.type==='select'?<select id={'setting-'+f.key} disabled={!enabled||busy} value={data[f.key]??''} onChange={e=>setData({...data,[f.key]:e.target.value})}><option value="">Tanlang</option>{f.options?.map(o=><option key={o}>{o}</option>)}</select>:<Input id={'setting-'+f.key} disabled={!enabled||busy} type={f.type||'text'} min={0} required={f.key==='centerName'} value={data[f.key]??''} onChange={e=>setData({...data,[f.key]:f.type==='number'&&e.target.value!==''?Number(e.target.value):e.target.value})}/>}</div>})}{error&&<p role="alert" className="form-error">{error}</p>}<p className="inline-notice">Faol sozlamalar saqlangach qo‘llanadi. “Hali ulanmagan” maydonlar hozir o‘zgartirilmaydi.</p></form></div>
}
