import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
export default function TelegramSettings(){
 const [open,setOpen]=useState(false),[token,setToken]=useState(''),[chatId,setChatId]=useState(''),[settings,setSettings]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){const r=await fetch('/api/crm/telegram');const d=await r.json();if(!r.ok)throw Error(d.error);setSettings(d);setChatId(d.chat_id||'')}
 useEffect(()=>{if(open){setToken('');setMessage('');load().catch(e=>setMessage(e.message))}},[open]);
 async function act(test=false){setBusy(true);setMessage('');try{const r=await fetch('/api/crm/telegram'+(test?'/test':''),{method:test?'POST':'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(test?{}:{token,chatId,enabled:settings.enabled,payments:settings.payments,reminders:settings.reminders})});const d=await r.json();if(!r.ok)throw Error(d.error);setToken('');await load();window.dispatchEvent(new Event('eduka-telegram-updated'));setMessage(test?'Sinov xabari guruhga yuborildi.':'Telegram sozlamalari saqlandi.')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 return <><Button variant="outline" onClick={()=>setOpen(true)}>Sozlash</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Telegram xabarlari</DialogTitle><DialogDescription>BotFather orqali bot yarating, botni guruhga qo‘shing va xabar yuborish ruxsatini bering.</DialogDescription></DialogHeader>{settings&&<form className="telegram-form" onSubmit={e=>{e.preventDefault();act()}}><label>Bot tokeni<Input type="password" autoComplete="new-password" value={token} onChange={e=>setToken(e.target.value)} placeholder={settings.configured?'Saqlangan. Almashtirish uchun yangi token kiriting':'123456789:AA…'} required={!settings.configured}/></label><label>Guruh IDsi<Input value={chatId} onChange={e=>setChatId(e.target.value)} placeholder="-1001234567890" required/></label>{settings.configured&&<p>@{settings.bot_username} · {settings.chat_title}</p>}{[['enabled','Xabar yuborish yoqilgan'],['payments','Qabul qilingan to‘lovlar'],['reminders','Bugungi topshiriq eslatmalari']].map(([key,label])=><label key={key}><input type="checkbox" checked={settings[key]} onChange={e=>setSettings({...settings,[key]:e.target.checked})}/> {label}</label>)}<p className="muted">Xabarlar avtomatik navbat bilan yuboriladi. Token qayta ko‘rsatilmaydi.</p><div className="flex gap-2"><Button disabled={busy} type="submit">{busy?'Tekshirilmoqda…':'Tekshirish va saqlash'}</Button><Button type="button" variant="outline" disabled={busy||!settings.configured||!settings.enabled} onClick={()=>act(true)}>Sinov xabari</Button></div></form>}{message&&<p role="status">{message}</p>}</DialogContent></Dialog></>
}
