'use client';
import {useEffect,useState} from 'react';
import {Plus,Pencil,Download,MapPin,Settings,ArrowUp,ArrowDown,Archive,LogOut,Check,FileText} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect} from '@/components/ui/native-select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {toast} from 'sonner';
import {requestReceipt} from './experience';
import {CRMRecord,studentAccount,displayName,groupIds,exportRows} from '@/lib/domain';
import {pages,fieldsFor,PageDef} from '@/lib/catalog';
const money=(v:any)=>new Intl.NumberFormat('uz-UZ').format(Number(v)||0);
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tashkent',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const localTime=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);
export function WorkflowTable({headers,rows,empty='Hozircha yozuvlar yo‘q'}:{headers:string[];rows:React.ReactNode[][];empty?:string}){return <div className="table-panel"><Table><TableHeader><TableRow>{headers.map((h,i)=><TableHead key={i}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((row,i)=><TableRow key={i}>{row.map((cell,j)=><TableCell key={j}>{cell}</TableCell>)}</TableRow>)}</TableBody></Table>{!rows.length&&<Empty><EmptyHeader><EmptyTitle>{empty}</EmptyTitle><EmptyDescription>Yozuv qo‘shilgach shu yerda ko‘rinadi.</EmptyDescription></EmptyHeader></Empty>}</div>}
const profileTabs=['Umumiy','Ota-onalar','Baholar','Izohlar','Fayllar','Guruhlar','Hisob-kitob','To‘lovlar','Davomat','Vazifalar','Qo‘ng‘iroqlar','Coin tarixi','LTV','Shartnomalar','Manzillar','Faollik','Shartnoma matni'];
export function Profile({student,records,events,close,edit,onAdd,onEdit,save}:{student:CRMRecord;records:CRMRecord[];events:any[];close:()=>void;edit:()=>void;onAdd:(entity:string,data?:any)=>void;onEdit:(r:CRMRecord)=>void;save:any}){
 const [tab,setTab]=useState('Umumiy'),[configure,setConfigure]=useState(false),[template,setTemplate]=useState('');
 const preference=records.find(r=>r.entity==='settings'&&r.data.section==='profile-tabs');
 const initialTabs=()=>{try{const p=JSON.parse(preference?.data.order??'[]');return Array.isArray(p)&&p.length?[...new Set([...p.filter(t=>profileTabs.includes(t)),...profileTabs])]:profileTabs}catch{return profileTabs}};
 const [order,setOrder]=useState<string[]>(initialTabs),[hidden,setHidden]=useState<string[]>(()=>{try{return JSON.parse(preference?.data.hidden??'[]')}catch{return []}});
 const label=(id:string)=>displayName(records.find(r=>r.id===id));const account=studentAccount(student.id,records);
 const related=(entity:string)=>records.filter(r=>r.entity===entity&&r.data.student===student.id);
 const add=(entity:string,extra:any={})=>onAdd(entity,{student:student.id,branch:student.data.branch??'',date:today(),month:today().slice(0,7),...extra});
 const rowsTable=(entity:string,keys:string[],headers:string[])=>{const definition=pages.find(p=>p.entity===entity&&p.fields.length);return <><div className="profile-actions"><Button onClick={()=>add(entity)}><Plus size={15}/>Qo‘shish</Button></div><WorkflowTable headers={[...headers,'']} rows={related(entity).map(r=>[...keys.map(k=>{const f=definition?.fields.find(f=>f.key===k);const v=r.data[k];return f?.type==='relation'?label(v):f?.type==='number'?money(v):f?.type==='file'&&v?<a className="blue-text" href={v} target="_blank" rel="noreferrer">Faylni ochish</a>:v||'—'}),<div className="flex gap-2"><button className="icon-button" aria-label="Tahrirlash" onClick={()=>onEdit(r)}><Pencil size={14}/></button>{entity==='transactions'&&<Button variant="outline" onClick={()=>requestReceipt(r,displayName(student))}>Chek</Button>}</div>])}/></>};
 const enrollments=related('enrollments');const legacyGroup=student.data.group&&!enrollments.some(r=>r.data.group===student.data.group)?records.find(r=>r.id===student.data.group):null;
 const groups=[...new Set([...enrollments.map(r=>r.data.group),...related('charges').map(r=>r.data.group),...related('transactions').map(r=>r.data.group),...(legacyGroup?[legacyGroup.id]:[])].filter(Boolean))];
 const ltvHeaders=['Guruh','O‘qigan davri','Holati','Hisoblangan','Chegirma','To‘langan','Qarz','O‘qituvchi ulushi'];
 const ltvRows=groups.map(id=>{const a=studentAccount(student.id,records,id),e=enrollments.find(r=>r.data.group===id);return [label(id),e?[e.data.startDate,e.data.endDate||'davom etmoqda'].join(' — '):'—',e?.data.status??'Faol',money(a.charged),money(a.discount),money(a.paid),money(a.debt),money(a.teacher)]});
 let balance=0;const coins=related('coins').slice().sort((a,b)=>a.created_at.localeCompare(b.created_at)).map(r=>{const before=balance;balance+=(r.data.direction==='Ayirish'?-1:1)*Number(r.data.amount||0);return [r.data.date,r.data.direction,money(r.data.amount),money(before),money(balance),r.data.reason||'—',<button className="icon-button" onClick={()=>onEdit(r)} aria-label="Tahrirlash"><Pencil size={14}/></button>]});
 const selectedTemplate=records.find(r=>r.id===template);const contract=String(selectedTemplate?.data.content??'').replaceAll('{{name}}',displayName(student)).replaceAll('{{date}}',today()).replaceAll('{{amount}}',money(account.charged));
 return <Dialog open onOpenChange={v=>!v&&close()}><DialogContent className="student-dialog"><DialogHeader><DialogTitle>O‘quvchi profili</DialogTitle><DialogDescription>{displayName(student)}</DialogDescription></DialogHeader><div className="student-layout"><aside className="student-card"><div className="student-avatar">{student.data.photo?<img src={student.data.photo} alt={displayName(student)} style={{width:'100%',height:'100%',objectFit:'cover',borderRadius:'inherit'}}/>:student.data.name?.slice(0,1)}</div><h2>{displayName(student)}</h2><span className="status-chip blue">{student.data.status||'Faol'}</span><div className="student-contact"><a href={'tel:'+student.data.phone}>{student.data.phone||'Telefon kiritilmagan'}</a><span>{student.data.email||'Email kiritilmagan'}</span></div><div className="profile-summary"><span>Balans<strong className={account.balance<0?'text-red-500':''}>{money(account.balance)} UZS</strong></span><span>To‘lanishi kerak<strong>{money(account.debt)} UZS</strong></span><span>To‘lovlar<strong>{money(account.paid)} UZS</strong></span><span>Coin<strong>{money(balance)}</strong></span></div><Button className="w-full" onClick={edit}><Pencil size={15}/>Tahrirlash</Button></aside><section className="student-main"><div className="profile-actions"><Button variant="outline" onClick={()=>setConfigure(true)}><Settings size={15}/>Tablarni sozlash</Button></div><Tabs value={tab} onValueChange={setTab}><TabsList className="profile-tabs">{order.filter(t=>!hidden.includes(t)).map(t=><TabsTrigger value={t} key={t}>{t}</TabsTrigger>)}</TabsList><TabsContent value="Umumiy"><div className="detail-grid">{fieldsFor(pages.find(p=>p.entity==='students')!).map(f=><div key={f.key}><span>{f.label}</span><strong>{f.type==='relation'?label(student.data[f.key]):f.type==='file'&&student.data[f.key]?<a href={student.data[f.key]} target="_blank" rel="noreferrer">Rasmni ochish</a>:String(student.data[f.key]??'—')}</strong></div>)}</div></TabsContent>
 <TabsContent value="Ota-onalar">{rowsTable('parents',['name','phone','note'],['Ism','Telefon','Izoh'])}<div className="detail-grid">{[['Ota',student.data.parentName,student.data.parentPhone],['Ona',student.data.motherName,student.data.motherPhone]].map(([title,name,phone])=><div key={title}><span>{title}</span><strong>{name||'—'}</strong>{phone&&<a href={'tel:'+phone}>{phone}</a>}</div>)}</div></TabsContent>
 <TabsContent value="Baholar">{rowsTable('assessments',['month','course','group','grade','note'],['Oy','Kurs','Guruh','Baho','Izoh'])}</TabsContent>
 <TabsContent value="Izohlar">{rowsTable('student-notes',['date','note'],['Sana','Izoh'])}</TabsContent>
 <TabsContent value="Fayllar">{rowsTable('student-files',['name','date','file','note'],['Nomi','Sana','Fayl','Izoh'])}</TabsContent>
 <TabsContent value="Guruhlar"><WorkflowTable headers={['Guruh','Kurs','O‘qituvchi','Dars vaqti']} rows={groupIds(student,records).map(id=>{const g=records.find(r=>r.id===id);return [label(id),label(g?.data.course),label(g?.data.teacher),[g?.data.days,g?.data.time].filter(Boolean).join(' · ')]})}/>{rowsTable('enrollments',['group','startDate','endDate','status','price'],['Guruh','Boshlanish','Tugash','Holati','Narx'])}{legacyGroup&&<p className="inline-notice">Oldingi biriktirish: {legacyGroup.data.name}. Yangi guruh biriktirishlari tarix bilan saqlanadi.</p>}</TabsContent>
 <TabsContent value="Hisob-kitob"><div className="mini-stats"><div><span>Hisoblangan</span><strong>{money(account.charged)}</strong></div><div><span>Chegirma</span><strong>{money(account.discount)}</strong></div><div><span>To‘lov</span><strong>{money(account.paid)}</strong></div></div><p className="form-note">Balans = boshlang‘ich qoldiq + kirim − qaytarilgan to‘lov − hisoblangan xarajat + chegirma. Xarajatlar “O‘quvchi hisob-kitobi” orqali kiritiladi.</p>{rowsTable('charges',['date','name','group','amount','teacherShare'],['Sana','Nomi','Guruh','Summa','O‘qituvchi ulushi'])}<h3>Chegirmalar tarixi</h3>{rowsTable('discounts',['date','name','group','amount','note'],['Sana','Nomi','Guruh','Summa','Izoh'])}</TabsContent>
 <TabsContent value="To‘lovlar"><div className="profile-actions"><Button onClick={()=>add('transactions',{direction:'Kirim'})}>To‘lov qabul qilish</Button><Button variant="outline" onClick={()=>add('transactions',{direction:'Chiqim',name:'To‘lovni qaytarish'})}>To‘lovni qaytarish</Button></div>{rowsTable('transactions',['date','name','group','amount','direction'],['Sana','Nomi','Guruh','Summa','Yo‘nalish'])}</TabsContent>
 <TabsContent value="Davomat">{rowsTable('attendance',['date','group','status','note'],['Sana','Guruh','Holati','Izoh'])}</TabsContent>
 <TabsContent value="Vazifalar">{rowsTable('student-tasks',['name','date','moderator','status'],['Nomi','Sana','Mas’ul','Holati'])}</TabsContent>
 <TabsContent value="Qo‘ng‘iroqlar">{rowsTable('calls',['date','type','moderator','duration','note'],['Sana','Turi','Xodim','Soniya','Izoh'])}<p className="form-note">Qo‘lda qayd etilgan qo‘ng‘iroqlar. Telefoniya ulanmagan.</p></TabsContent>
 <TabsContent value="Coin tarixi"><div className="profile-actions"><Button onClick={()=>add('coins')}>Coin operatsiyasi</Button></div><WorkflowTable headers={['Sana','Turi','Miqdor','Avvalgi balans','Yangi balans','Sabab','']} rows={coins}/><p className="form-note">Qo‘lda kiritilgan operatsiyalar bo‘yicha hisoblanadi.</p></TabsContent>
 <TabsContent value="LTV"><div className="profile-actions"><Button variant="outline" onClick={()=>exportRows('LTV',ltvHeaders,ltvRows)}><Download size={15}/>Eksport</Button></div><WorkflowTable headers={ltvHeaders} rows={ltvRows}/><p className="form-note">Guruhga biriktirilgan xarajatlar va to‘lovlar jamlanmasi. Guruhsiz operatsiyalar umumiy balansda qoladi.</p></TabsContent>
 <TabsContent value="Shartnomalar">{rowsTable('student-contracts',['number','type','date','file'],['Raqami','Turi','Sana','Fayl'])}</TabsContent>
 <TabsContent value="Manzillar">{rowsTable('addresses',['name','type','address'],['Nomi','Turi','Manzil'])}{related('addresses').filter(r=>r.data.latitude!==undefined&&r.data.longitude!==undefined&&r.data.latitude!==''&&r.data.longitude!=='').map(r=><div className="address-map" key={r.id}><strong>{r.data.name}</strong><iframe title={r.data.name+' xaritasi'} loading="lazy" src={'https://www.openstreetmap.org/export/embed.html?bbox='+[Number(r.data.longitude)-.01,Number(r.data.latitude)-.01,Number(r.data.longitude)+.01,Number(r.data.latitude)+.01].join(',')+'&layer=mapnik&marker='+r.data.latitude+','+r.data.longitude}/></div>)}</TabsContent>
 <TabsContent value="Faollik"><div className="activity-list">{events.filter(e=>e.record_id===student.id||records.some(r=>r.id===e.record_id&&r.data.student===student.id)).map((e,i)=><div key={i}><i/><div><strong>{e.action==='create'?'Yaratildi':e.action==='update'?'Tahrirlandi':e.action==='archive'?'Arxivlandi':'Tiklandi'}</strong><span>{e.actor||'Administrator'} · {new Date(e.created_at).toLocaleString('uz-UZ')}</span>{e.changes&&Object.entries(e.changes).map(([key,v]:any)=><p className="audit-change" key={key}>{fieldsFor(pages.find(p=>p.entity==='students')!).find(f=>f.key===key)?.label||key}: {String(v.before??'—')} → {String(v.after??'—')}</p>)}</div></div>)}</div></TabsContent>
 <TabsContent value="Shartnoma matni"><NativeSelect value={template} onChange={e=>setTemplate(e.target.value)}><option value="">Shablonni tanlang</option>{records.filter(r=>r.entity==='contract-templates').map(r=><option key={r.id} value={r.id}>{r.data.name}</option>)}</NativeSelect>{template&&<><article className="contract-preview"><h2>{selectedTemplate?.data.name}</h2><p>{contract}</p></article><Button onClick={()=>{const b=new Blob([contract],{type:'text/plain;charset=utf-8'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='Shartnoma.txt';a.click();URL.revokeObjectURL(u)}}><Download size={15}/>Yuklash</Button></>}</TabsContent></Tabs></section></div>
 <Dialog open={configure} onOpenChange={setConfigure}><DialogContent><DialogHeader><DialogTitle>Profil tablarini sozlash</DialogTitle><DialogDescription>Ko‘rinadigan bo‘limlar va ularning tartibi.</DialogDescription></DialogHeader><div className="tab-preferences">{order.map((t,i)=><div key={t}><Checkbox checked={!hidden.includes(t)} onCheckedChange={v=>setHidden(h=>v?h.filter(x=>x!==t):[...h,t])}/><span>{t}</span><button aria-label="Yuqoriga" disabled={i===0} onClick={()=>setOrder(o=>{const a=[...o];[a[i-1],a[i]]=[a[i],a[i-1]];return a})}><ArrowUp size={15}/></button><button aria-label="Pastga" disabled={i===order.length-1} onClick={()=>setOrder(o=>{const a=[...o];[a[i],a[i+1]]=[a[i+1],a[i]];return a})}><ArrowDown size={15}/></button></div>)}</div><DialogFooter><Button variant="outline" onClick={()=>{setOrder(profileTabs);setHidden([])}}>Standart</Button><Button onClick={async()=>{if(hidden.length===order.length){toast.error('Kamida bitta tab qolsin');return}try{await save('settings',{section:'profile-tabs',order:JSON.stringify(order),hidden:JSON.stringify(hidden)},preference);if(hidden.includes(tab))setTab(order.find(t=>!hidden.includes(t))!);setConfigure(false);toast.success('Saqlandi')}catch(e:any){toast.error(e.message)}}}>Saqlash</Button></DialogFooter></DialogContent></Dialog>
 </DialogContent></Dialog>
}
export function Visits({rows,records,save,onAdd,onEdit}:{rows:CRMRecord[];records:CRMRecord[];save:any;onAdd:()=>void;onEdit:(r:CRMRecord)=>void}){const [busy,setBusy]=useState('');const leave=async(r:CRMRecord)=>{setBusy(r.id);try{await save('visits',{...r.data,leftAt:localTime()},r);toast.success('Ketish qayd etildi')}catch(e:any){toast.error(e.message)}finally{setBusy('')}};return <><div className="visit-summary"><span><strong>{rows.filter(r=>!r.data.leftAt).length}</strong> o‘quvchi ichkarida</span><Button onClick={onAdd}><Plus size={15}/>Kelishni qayd etish</Button></div><WorkflowTable headers={['O‘quvchi','Kelish vaqti','Ketish vaqti','Holati','Amallar']} rows={rows.map(r=>[displayName(records.find(s=>s.id===r.data.student)),r.data.arrivedAt?.replace('T',' '),r.data.leftAt?.replace('T',' ')||'—',r.data.leftAt?'Ketgan':'Ichkarida',<div className="flex gap-2">{!r.data.leftAt&&<Button disabled={busy===r.id} variant="outline" onClick={()=>leave(r)}><LogOut size={14}/>Ketdi</Button>}<button className="icon-button" onClick={()=>onEdit(r)} aria-label="Tahrirlash"><Pencil size={14}/></button></div>])}/></>}
export function BusinessReport({kind,rows,records,label,title}:{kind:string;rows:CRMRecord[];records:CRMRecord[];label:(id:any)=>string;title:string}){let headers:string[]=[],data:any[][]=[];
 if(kind==='debt'){headers=['O‘quvchi','Telefon','Hisoblangan','To‘langan','Chegirma','Qarz','Limit'];data=rows.filter(r=>r.entity==='students').map(r=>{const a=studentAccount(r.id,records);return [label(r.id),r.data.phone||'—',money(a.charged),money(a.paid),money(a.discount),money(a.debt),money(r.data.debtLimit)]}).filter(r=>r[5]!=='0');}
 if(kind==='earned'){headers=['O‘quvchi','Guruh','Sana','Hisoblangan daromad','O‘qituvchi ulushi'];data=rows.map(r=>[label(r.data.student),label(r.data.group),r.data.date,money(r.data.amount),money(r.data.teacherShare)]);}
 if(kind==='price-difference'){headers=['O‘quvchi','Guruh','Guruh narxi','Kelishilgan narx','Tafovut'];data=records.filter(r=>r.entity==='enrollments'&&rows.some(g=>g.id===r.data.group)).map(r=>{const g=records.find(g=>g.id===r.data.group);return [label(r.data.student),label(r.data.group),money(g?.data.price),money(r.data.price),money(Number(g?.data.price||0)-Number(r.data.price||0))]});}
 if(kind==='coins'){headers=['O‘quvchi','Sana','Turi','Miqdor','Sabab'];data=rows.map(r=>[label(r.data.student),r.data.date,r.data.direction,money(r.data.amount),r.data.reason]);}
 if(kind==='missing-attendance'){headers=['Guruh','O‘qituvchi','Oxirgi qayd'];data=rows.filter(r=>r.entity==='groups'&&!records.some(a=>a.entity==='attendance'&&a.data.group===r.id&&a.data.date===today())).map(r=>[label(r.id),label(r.data.teacher),records.filter(a=>a.entity==='attendance'&&a.data.group===r.id).map(a=>a.data.date).sort().reverse()[0]||'Davomat yo‘q']);}
 return <><div className="profile-actions"><Button variant="outline" onClick={()=>exportRows(title,headers,data)}><Download size={15}/>Hisobotni eksport qilish</Button></div><WorkflowTable headers={headers} rows={data}/>{kind==='missing-attendance'&&<p className="form-note">Bugun davomat qaydi mavjud bo‘lmagan guruhlar. Dam olish yoki dars bo‘lmagan kunlarni ham tekshiring.</p>}{kind==='earned'&&<p className="form-note">Qo‘lda kiritilgan dars xarajatlari bo‘yicha daromad.</p>}</>}
