export type Field = {key:string;label:string;type?:string;required?:boolean;options?:string[];entity?:string};
export type PageDef={path:string;title:string;entity:string;fields:Field[];kind?:string;filter?:string;readonly?:boolean};
const f=(key:string,label:string,type='text',required=false,options?:string[],entity?:string):Field=>({key,label,type,required,options,entity});
const name=f('name','Nomi','text',true), note=f('note','Izoh','textarea'), date=f('date','Sana','date',true), amount=f('amount','Summa','number',true), student=f('student','O‘quvchi','relation',true,undefined,'students'), group=f('group','Guruh','relation',false,undefined,'groups'), teacher=f('teacher','O‘qituvchi','relation',false,undefined,'employees'), course=f('course','Kurs','relation',false,undefined,'courses'), moderator=f('moderator','Mas’ul xodim','relation',false,undefined,'employees'), phone=f('phone','Telefon','tel'), branch=f('branch','Filial','relation',false,undefined,'branches');
const status=f('status','Holati','select',false,['Faol','Arxiv','Muzlatilgan']);
export const studentFields=[f('name','Ism','text',true),f('surname','Familiya'),f('fatherName','Otasining ismi'),phone,f('email','Email','email'),f('birthDate','Tug‘ilgan sana','date'),f('category','Kategoriya','relation',false,undefined,'student-categories'),f('source','Qayerdan keldi?'),f('language','Til','select',false,['O‘zbek','Rus','Ingliz']),f('paymentDate','To‘lov sanasi','date'),group,moderator,status,f('parentName','Otasining ismi'),f('parentPhone','Otasining telefoni','tel'),f('fatherJob','Otasining ish joyi'),f('motherName','Onasining ismi'),f('motherPhone','Onasining telefoni','tel'),f('motherJob','Onasining ish joyi'),f('targetUniversity','Maqsad universitet'),f('address','Manzil'),f('school','O‘qish joyi'),f('tags','Hashtaglar'),f('exitReason','Ketish sababi'),f('debtLimit','Qarzdorlik limiti','number'),branch,note];
const transactionFields=[f('name','Tranzaksiya nomi','text',true),amount,f('direction','Yo‘nalish','select',true,['Kirim','Chiqim']),date,f('student','O‘quvchi','relation',false,undefined,'students'),f('cash','Kassa','relation',true,undefined,'cash'),f('paymentMethod','To‘lov usuli','select',true,['Naqd','Karta','Bank o‘tkazmasi']),f('category','Kategoriya','relation',false,undefined,'payment-type'),group,branch,f('flow','Faoliyat turi','select',false,['Operatsion','Investitsion','Moliyaviy']),note];
export const menus:{title:string;icon:string;pages:PageDef[]}[]=[
{title:'Topshiriqlar',icon:'tasks',pages:[{path:'/tasks',title:'Topshiriqlar',entity:'tasks',kind:'tasks',fields:[name,date,f('time','Vaqt','time'),moderator,f('type','Topshiriq turi','select',false,['Qo‘ng‘iroq','Uchrashuv','Nazorat','Boshqa']),f('status','Holati','select',false,['Yangi','Jarayonda','Bajarilgan']),note]}]},
{title:'Lidlar',icon:'leads',pages:[{path:'/orders/order-list/table',title:'Buyurtmalar',entity:'orders',kind:'leads',fields:[name,phone,f('student','O‘quvchi','relation',false,undefined,'students'),course,group,teacher,moderator,f('source','Reklama manbasi'),f('day','Dars kunlari','select',false,['Toq kunlar','Juft kunlar','Har kuni','Dam olish kuni']),f('time','Dars vaqti','time'),f('date','Birinchi dars sanasi','date'),f('status','Holati','select',true,['Yangi','Imtihonga yozildi','Test yechdi','Shartnoma','Bekor qilindi']),note]},{path:'/orders/come-orders',title:'Birinchi darsga keladiganlar',entity:'orders',filter:'trial',fields:[]}]},
{title:'Guruh',icon:'groups',pages:[{path:'/group/groups',title:'Guruhlar',entity:'groups',fields:[name,course,teacher,branch,f('type','Turi','select',false,['Oddiy','Individual','Maktab']),f('room','Xona','relation',false,undefined,'rooms'),f('days','Kunlar','select',false,['Toq kunlar','Juft kunlar','Har kuni','Dam olish kuni']),f('time','Boshlanish vaqti','time'),f('endTime','Tugash vaqti','time'),f('startDate','Boshlanish sanasi','date'),f('endDate','Tugash sanasi','date'),f('price','Oylik to‘lov','number'),f('telegram','Telegram havolasi','url'),status,note]},{path:'/group/tasks',title:'Imtihon va vazifalar',entity:'exams',fields:[name,date,group,teacher,f('maxPoint','Maksimal ball','number'),note]},{path:'/group/class-schedule',title:'Dars jadvali',entity:'groups',kind:'schedule',fields:[]},{path:'/group/rooms',title:'Xonalar',entity:'rooms',fields:[name,f('capacity','Sig‘im','number'),moderator,branch,note]},{path:'/group/equipments',title:'Jihozlar',entity:'equipments',fields:[name,f('inventory','Inventar raqami'),f('price','Narxi','number'),f('room','Xona','relation',false,undefined,'rooms'),note]},{path:'/group/group-students',title:'Guruh o‘quvchilari',entity:'students',fields:[],readonly:true}]},
{title:'O‘quvchilar',icon:'students',pages:[{path:'/orders/new-student-list',title:'Yangi o‘quvchilar',entity:'students',filter:'new',fields:studentFields},{path:'/students/active',title:'Faol o‘quvchilar',entity:'students',filter:'Faol',fields:studentFields},{path:'/students/archive',title:'Arxiv o‘quvchilar',entity:'students',filter:'Arxiv',fields:studentFields},{path:'/students/student-list',title:'Barcha o‘quvchilar',entity:'students',fields:studentFields},{path:'/students/parent',title:'Ota-onalar',entity:'parents',fields:[name,phone,student,note]},{path:'/students/debt-risk',title:'Qarzdorlik xavfi',entity:'students',kind:'unverified',fields:[],readonly:true},{path:'/students/locations',title:'O‘quvchilar manzili',entity:'students',kind:'locations',fields:[],readonly:true}]},
{title:'O‘quv bo‘limi',icon:'study',pages:[{path:'/course/courses',title:'Kurslar',entity:'courses',fields:[name,f('color','Rang','color'),branch,f('price','Bir dars narxi','number'),f('monthlyPrice','Oylik narxi','number'),note]},{path:'/online-course',title:'Onlayn kurslar',entity:'online-courses',fields:[name,f('description','Tavsif','textarea'),f('language','Til','select',false,['O‘zbek','Rus','Ingliz']),f('level','Daraja'),f('category','Kategoriya','relation',false,undefined,'online-course-categories'),f('outcomes','Nimalar o‘rganiladi?','textarea'),f('image','Rasm (750 × 422)','file'),f('video','Video havolasi','url'),f('requirements','Talablar','textarea'),f('price','Narx','number')]},{path:'/online-course-category',title:'Onlayn kurs kategoriyalari',entity:'online-course-categories',fields:[name,note]},{path:'/seasonal-assessment',title:'Oylik baholash',entity:'assessments',fields:[student,course,group,f('month','Oy','month'),f('grade','Baho','number'),note]},{path:'/course/contracts',title:'Shartnoma shablonlari',entity:'contract-templates',fields:[name,f('type','Turi','select',false,['O‘quvchi','Xodim']),f('content','Shartnoma matni: {{name}}, {{date}}, {{amount}}','textarea')]},{path:'/admission/banks',title:'Savollar banki',entity:'question-banks',fields:[name,course,f('duration','Davomiylik (daqiqa)','number'),f('point','Ball','number'),f('questions','Savollar va javoblar','textarea'),status]}]},
{title:'Blok test',icon:'test',pages:[{path:'/block-test/types',title:'Test turlari',entity:'test-types',fields:[name,f('subjects','Fanlar'),f('questionCount','Savollar soni','number'),f('point','Ball','number')]},{path:'/block-test/exams',title:'Blok imtihonlar',entity:'block-exams',fields:[name,f('type','Test turi','relation',true,undefined,'test-types'),date,f('time','Vaqt','time'),f('duration','Davomiylik (daqiqa)','number'),group,moderator,note]}]},
{title:'Moliya',icon:'finance',pages:[{path:'/finance/cash',title:'Kassalar',entity:'cash',fields:[name,moderator,f('online','Onlayn to‘lov qabul qilish','checkbox'),status]},{path:'/finance/payment-type',title:'Tranzaksiya turlari',entity:'payment-type',fields:[name,f('color','Rang','color'),f('direction','Yo‘nalish','select',true,['Kirim','Chiqim','Bonus','Jarima']),f('minimum','Minimal summa','number'),f('maximum','Maksimal summa','number'),f('clientType','Mijoz turi','select',false,['O‘quvchi','Xodim','Hamkor']),note]},{path:'/finance/transactions',title:'Tranzaksiyalar',entity:'transactions',fields:transactionFields},{path:'/finance/planned-expense',title:'Rejalashtirilgan xarajatlar',entity:'planned-expenses',fields:[name,amount,f('category','Kategoriya','relation',false,undefined,'payment-type'),f('startDate','Boshlanish sanasi','date'),f('endDate','Tugash sanasi','date'),f('status','Holati','select',false,['Rejada','To‘langan','Bekor qilingan']),note]},{path:'/finance/contract',title:'Bo‘lib to‘lash',entity:'installments',fields:[student,amount,date,f('paid','To‘langan summa','number'),f('parts','To‘lov qismlari','parts'),branch,note]},{path:'/finance/bonus',title:'Bonuslar',entity:'bonuses',fields:[moderator,amount,date,note]},{path:'/finance/penalty',title:'Jarimalar',entity:'penalties',fields:[moderator,amount,date,note,f('image','Rasm','file')]},{path:'/finance/salary',title:'Ish haqi',entity:'salary',fields:[moderator,f('month','Oy','month'),f('base','Asosiy maosh','number'),f('bonus','Bonus','number'),f('advance','Avans','number'),f('penalty','Jarima','number'),note]},{path:'/analytics/finance',title:'Moliyaviy tahlil',entity:'transactions',kind:'finance',fields:[]},{path:'/analytics/income-plan',title:'Kirim rejasi',entity:'income-plans',fields:[name,f('month','Oy','month'),amount,moderator]},{path:'/analytics/financial-analytics',title:'Moliyaviy analitika',entity:'transactions',kind:'finance',fields:[]},{path:'/analytics/financial-reports',title:'Moliyaviy hisobotlar',entity:'transactions',kind:'finance',fields:[]},{path:'/finance/pnl-reports',title:'P&L hisoboti',entity:'transactions',kind:'pnl',fields:[]},{path:'/finance/cashflow',title:'Pul oqimi',entity:'transactions',kind:'cashflow',fields:[]}]},
{title:'Nazorat',icon:'control',pages:[{path:'/students/attendance',title:'Davomat',entity:'attendance',fields:[student,group,teacher,date,f('status','Davomat holati','select',true,['Keldi','Sababli','Sababsiz','Birinchi dars','Muzlatilgan']),note]},{path:'/analytics/attendance',title:'Davomat tahlili',entity:'attendance',kind:'attendance',fields:[]},{path:'/feedback',title:'Taklif va shikoyatlar',entity:'feedback',fields:[name,phone,f('type','Turi','select',false,['Taklif','Shikoyat']),branch,date,note]},{path:'/hr/employees/ratings',title:'O‘qituvchi reytingi',entity:'ratings',fields:[student,teacher,course,group,date,f('rating','Reyting (1–5)','number'),note]},{path:'/analytics/not-attended',title:'Davomat olinmagan darslar',entity:'groups',kind:'unverified',fields:[],readonly:true},{path:'/monitoring/statistics',title:'Statistika',entity:'students',kind:'statistics',fields:[]},{path:'/analytics/turnstile',title:'Turniket',entity:'turnstile',kind:'integration',fields:[],readonly:true},{path:'/analytics/turnstile-enter-exit',title:'Kirish-chiqish',entity:'turnstile',kind:'integration',fields:[],readonly:true},{path:'/nazorat/support-analytics',title:'Support tahlili',entity:'support',fields:[student,course,teacher,date,f('time','Vaqt','time'),f('count','Soni','number'),note]}]},
{title:'Boshqaruv',icon:'management',pages:[{path:'/hr/employees',title:'Xodimlar',entity:'employees',fields:[f('name','Ism','text',true),f('surname','Familiya','text',true),f('phone','Telefon','tel',true),f('role','Lavozim','relation',true,undefined,'roles'),f('gender','Jinsi','select',false,['Erkak','Ayol']),f('birthDate','Tug‘ilgan sana','date'),f('email','Email','email'),branch,f('schedule','Ish grafigi','relation',false,undefined,'work-schedules'),f('salary','Asosiy oylik','number'),f('lessonRate','Bir dars uchun haq','number'),f('revenuePercent','Guruh tushumidan foiz (0–100)','number'),f('image','Profil rasmi','file'),note]},{path:'/hr/roles',title:'Rollar',entity:'roles',kind:'roles',fields:[name,note,f('bossOnly','Faqat rahbar','checkbox'),f('permissions','Ruxsatlar','permissions')]},{path:'/branches',title:'Filiallar',entity:'branches',fields:[name,f('address','Manzil'),f('latitude','Kenglik','number'),f('longitude','Uzunlik','number'),f('radius','Radius (metr)','number'),f('maxGroups','Maksimal guruhlar','number'),f('maxStudents','Maksimal o‘quvchilar','number'),f('image','Filial rasmi','file')]},{path:'/hr/work-schedules',title:'Ish grafiklari',entity:'work-schedules',fields:[name,f('year','Yil','number'),f('code','Kod'),f('weekdays','Hafta kunlari'),f('startTime','Kelish vaqti','time'),f('endTime','Ketish vaqti','time'),f('breakStart','Tanaffus boshi','time'),f('breakEnd','Tanaffus oxiri','time'),note]}]},
{title:'Sotuv va marketing',icon:'marketing',pages:[{path:'/marketing/surveys',title:'So‘rovnomalar',entity:'surveys',fields:[name,f('subtitle','Sarlavha osti'),f('image','Rasm','file'),f('amount','Summa','number'),f('language','Til','select',false,['O‘zbek','Rus']),f('visible','Ko‘rsatish','checkbox'),branch]},{path:'/marketing/sales-plan',title:'Sotuv rejasi',entity:'sales-plans',fields:[moderator,f('month','Oy','month'),f('plan','Reja','number'),f('paymentCount','To‘lovlar soni','number')]},{path:'/news/news-list',title:'Yangiliklar',entity:'news',fields:[name,f('image','Rasm (1000 × 700)','file'),f('content','Matn','textarea'),f('audience','Kimga','select',false,['O‘quvchilar','Ota-onalar','Xodimlar','Barchaga']),branch,date]},{path:'/story/pagin',title:'Stories',entity:'stories',fields:[name,f('media','Rasm yoki video','file'),group,branch]},{path:'/news/sms-template',title:'SMS shablonlar',entity:'sms-templates',fields:[name,f('type','Turi','select',true,['Eslatma','To‘lov','Davomat','Tabrik']),f('content','SMS matni','textarea',true)]},{path:'/news/sms',title:'SMS xabarlar',entity:'sms',kind:'integration',fields:[],readonly:true}]},
{title:'Hisobotlar',icon:'reports',pages:[
['/analytics/order','Buyurtmalar hisoboti','orders','funnel'],['/reports/finance/balance','Xodimlar balansi','salary','salary'],['/reports/analytics/finance','Moliyaviy tahlil','transactions','finance'],['/reports/analytics/income-plan','Kirim rejasi','income-plans','table'],['/reports/analytics/unpaid','Qarzdorlar','students','unverified'],['/reports/analytics/different','Narx tafovuti','groups','unverified'],['/analytics/cancelled-transactions','Bekor qilingan tranzaksiyalar','transactions','cancelled'],['/analytics/general-discounts','Chegirmalar','discounts','table'],['/analytics/teacher','O‘qituvchi hisoboti','employees','report'],['/analytics/moderator/student','Moderator hisoboti','employees','report'],['/statistics','Ketish sabablari','students','report'],['/analytics/rooms','Xonalar bandligi','rooms','report'],['/analytics/earned-analytics','Ishlab topilgan daromad','transactions','unverified'],['/analytics/attendance-cancelled-analytics','Bekor qilingan davomat','attendance','cancelled'],['/reports/monitoring/statistics','Umumiy statistika','students','statistics'],['/reports/hr/employees/ratings','Reyting hisoboti','ratings','table'],['/reports/analytics/not-attended','Davomat olinmaganlar','groups','unverified']
].map(([path,title,entity,kind])=>({path,title,entity,kind,fields:[],readonly:true}))},
{title:'Sozlamalar',icon:'settings',pages:[['system','Tizim sozlamalari'],['finance','Moliya sozlamalari'],['study','O‘quv bo‘limi sozlamalari'],['sale-marketing','Sotuv va marketing'],['management','Boshqaruv sozlamalari'],['app-settings','Ilova sozlamalari'],['integration','Integratsiyalar'],['gamification','Gamifikatsiya']].map(([key,title])=>({path:'/settings/'+key,title,entity:'settings',kind:key==='integration'?'integrations':key==='gamification'?'unverified':'settings',fields:[]}))}
];
const supplemental:PageDef[]=[
 {path:'/students/rewards',title:'Mukofotlar',entity:'rewards',fields:[name,f('cost','Narxi (coin)','number',true),f('stock','Qoldiq','number',true),note]},
 {path:'/students/enrollments',title:'Guruhga biriktirish',entity:'enrollments',fields:[student,f('group','Guruh','relation',true,undefined,'groups'),f('startDate','Boshlanish sanasi','date',true),f('endDate','Tugash sanasi','date'),f('status','Holati','select',true,['Faol','Muzlatilgan','Yakunlangan']),f('price','Kelishilgan narx','number'),note]},
 {path:'/students/attendance/viewing',title:'Kirish va chiqish',entity:'visits',kind:'visits',fields:[student,f('arrivedAt','Kelish vaqti','datetime-local',true),f('leftAt','Ketish vaqti','datetime-local'),branch,note]},
 {path:'/finance/charges',title:'O‘quvchi hisob-kitobi',entity:'charges',fields:[student,group,name,date,amount,f('teacherShare','O‘qituvchi ulushi','number'),branch,note]},
 {path:'/students/addresses',title:'Manzillar',entity:'addresses',fields:[student,name,f('type','Manzil turi','select',true,['Uy','O‘qish joyi','Boshqa']),f('address','Manzil','text',true),f('latitude','Kenglik','number'),f('longitude','Uzunlik','number'),note]},
 {path:'/students/contracts',title:'O‘quvchi shartnomalari',entity:'student-contracts',fields:[student,f('number','Shartnoma raqami','text',true),f('type','Shartnoma turi'),date,f('file','Shartnoma fayli','file',true),note]},
 {path:'/students/calls',title:'Qo‘ng‘iroqlar jurnali',entity:'calls',fields:[student,date,moderator,f('type','Turi','select',true,['Kiruvchi','Chiquvchi']),f('duration','Davomiylik (soniya)','number'),note]},
 {path:'/students/tasks',title:'O‘quvchi vazifalari',entity:'student-tasks',fields:[student,name,date,moderator,f('status','Holati','select',true,['Yangi','Jarayonda','Bajarilgan']),note]},
 {path:'/students/coins',title:'Coin operatsiyalari',entity:'coins',fields:[student,f('direction','Turi','select',true,['Qo‘shish','Ayirish']),f('amount','Miqdor','number',true),date,f('reason','Sababi','text',true),note]},
 {path:'/settings/student-categories',title:'O‘quvchi kategoriyalari',entity:'student-categories',fields:[name,f('color','Rang','color'),note]},
 {path:'/finance/discounts',title:'Chegirmalar',entity:'discounts',fields:[student,group,name,date,amount,note]},
 {path:'/settings/holidays',title:'Bayram kunlari',entity:'holidays',fields:[name,f('startDate','Boshlanish','date',true),f('endDate','Tugash','date',true),note]}
];
menus.find(m=>m.title==='O‘quvchilar')!.pages.push(...supplemental.filter(p=>p.path.startsWith('/students/')));
menus.find(m=>m.title==='Moliya')!.pages.push(...supplemental.filter(p=>p.path.startsWith('/finance/')));
menus.find(m=>m.title==='Sozlamalar')!.pages.push(...supplemental.filter(p=>p.path.startsWith('/settings/')));
const configure=(path:string,patch:Partial<PageDef>)=>{const p=menus.flatMap(m=>m.pages).find(p=>p.path===path);if(p)Object.assign(p,patch)};
configure('/students/debt-risk',{kind:'debt'});configure('/reports/analytics/unpaid',{kind:'debt'});
configure('/analytics/earned-analytics',{kind:'earned',entity:'charges'});configure('/settings/gamification',{kind:'coins',entity:'coins',fields:supplemental.find(p=>p.entity==='coins')!.fields});
configure('/analytics/not-attended',{kind:'missing-attendance'});configure('/reports/analytics/not-attended',{kind:'missing-attendance'});
configure('/reports/analytics/different',{kind:'price-difference'});
export const pages=menus.flatMap(m=>m.pages);
export const findPage=(path:string)=>pages.find(p=>p.path===path);
export const fieldsFor=(page:PageDef)=>page.fields.length?page.fields:pages.find(p=>p.entity===page.entity&&p.fields.length)?.fields??[name,date,note];
export const entityAllowlist=[...new Set([...pages.map(p=>p.entity),'student-categories','calls','student-tasks','holidays','partners','payment-methods','discounts','exit-reasons','activities','assessment-levels','call-statuses','tags','teacher-grades','events'])];
