export const settingsSections:Record<string,Record<string,{label:string;key:string;type?:string;options?:string[]}[]>>={
system:{
 'Moliya':[{key:'monthlyPricing',label:'Oylik narxlash',type:'switch'},{key:'retainPrice',label:'Guruh almashtirganda narxni saqlash',type:'switch'},{key:'transferConfirm',label:'Kassa o‘tkazmasini tasdiqlash',type:'switch'},{key:'cancelNote',label:'Bekor qilishda izoh talab qilish',type:'switch'},{key:'currency',label:'Valyuta',type:'select',options:['UZS','USD']},{key:'debtLimit',label:'Qarzdorlik limiti',type:'number'}],
 'Davomat':[{key:'oldAttendance',label:'O‘tgan darslar davomatini tahrirlash',type:'switch'},{key:'defaultPresent',label:'Boshlang‘ich holat: keldi',type:'switch'},{key:'autoExit',label:'Kelmagan o‘quvchini avtomatik chiqarish',type:'switch'},{key:'maxGrade',label:'Maksimal baho',type:'number'}],
 'O‘qituvchi':[{key:'teacherBusy',label:'O‘qituvchi bandligini ko‘rsatish',type:'switch'},{key:'teacherFinance',label:'Moliyaviy filtr',type:'switch'},{key:'supportTeacher',label:'Support o‘qituvchi',type:'switch'},{key:'salaryIndicator',label:'Ish haqi ko‘rsatkichi',type:'switch'}],
 'Xonalar':[{key:'roomBusy',label:'Xona bandligini ko‘rsatish',type:'switch'},{key:'roomCapacity',label:'Xona sig‘imini nazorat qilish',type:'switch'}],
 'Topshiriqlar':[{key:'employeeTasks',label:'Xodimlar topshiriqlari',type:'switch'},{key:'leadFollowup',label:'Lid bilan qayta bog‘lanish',type:'switch'},{key:'expiryReminder',label:'Muddati tugashini eslatish',type:'switch'}],
 'Foydalanuvchilar':[{key:'requiredBirthDate',label:'Tug‘ilgan sana majburiy',type:'switch'},{key:'requiredPhone',label:'Telefon raqami majburiy',type:'switch'},{key:'requiredSource',label:'Reklama manbasi majburiy',type:'switch'}],
 'Vaqt va jadval':[{key:'timezone',label:'Vaqt mintaqasi',type:'select',options:['Asia/Tashkent']},{key:'dayStart',label:'Ish kuni boshlanishi',type:'time'},{key:'dayEnd',label:'Ish kuni tugashi',type:'time'},{key:'archiveDays',label:'Arxiv saqlanishi (kun)',type:'number'}],
 'Chek':[{key:'receiptTitle',label:'Chek sarlavhasi'},{key:'receiptFooter',label:'Pastki matn'},{key:'receiptFontSize',label:'Shrift o‘lchami',type:'number'},{key:'receiptQR',label:'QR kod',type:'switch'},{key:'autoPrint',label:'Avtomatik chop etish',type:'switch'}],
 'Foydalanuvchi sozlamalari':[{key:'filterStyle',label:'Filtr ko‘rinishi',type:'select',options:['Oddiy','Yig‘iladigan','Modal']},{key:'tablePageSize',label:'Jadvaldagi qatorlar soni',type:'select',options:['10','20','50']}]
},
finance:{'Hamkorlar':[{key:'partnersNote',label:'Hamkorlik shartlari'}],'KPI':[{key:'kpiTarget',label:'Oylik maqsad',type:'number'},{key:'managerBonus',label:'Moderator bonusi (%)',type:'number'}],'Ish haqi foizi':[{key:'teacherPercent',label:'O‘qituvchi ulushi (%)',type:'number'}],'Avtomatik chegirmalar':[{key:'twoGroups',label:'2 guruh uchun chegirma (%)',type:'number'},{key:'threeGroups',label:'3 guruh uchun chegirma (%)',type:'number'},{key:'fourGroups',label:'4 guruh uchun chegirma (%)',type:'number'}]},
study:{'Sabablar':[{key:'attendanceReasons',label:'Davomat sabablari (vergul bilan)'},{key:'exitReasons',label:'Ketish sabablari (vergul bilan)'},{key:'trialFree',label:'Sinov darsidan keyin to‘lov olmaslik',type:'switch'}],'Mashg‘ulotlar':[{key:'maxCapacity',label:'Maksimal sig‘im',type:'number'},{key:'lessonDuration',label:'Dars davomiyligi (daqiqa)',type:'number'}],'Baholash':[{key:'minPercent',label:'Minimal foiz',type:'number'},{key:'maxPercent',label:'Maksimal foiz',type:'number'}]},
'sale-marketing':{'Qo‘ng‘iroqlar':[{key:'callStatuses',label:'Qo‘ng‘iroq holatlari'}],'Hashtaglar':[{key:'tags',label:'Hashtaglar (vergul bilan)'}],'Kategoriyalar':[{key:'categories',label:'O‘quvchi kategoriyalari'}],'Avto SMS':[{key:'smsPayment',label:'To‘lov eslatmasi',type:'switch'},{key:'smsAbsence',label:'Davomat xabari',type:'switch'},{key:'smsDelay',label:'Kechikish (daqiqa)',type:'number'},{key:'absenceCount',label:'Kelmagan darslar soni',type:'number'}],'Telegram eslatmalari':[{key:'telegramTemplate',label:'Eslatma matni'}]},
management:{'Moderator darajalari':[{key:'managerGrade',label:'Daraja nomi'},{key:'managerFull',label:'To‘liq maosh','type':'number'},{key:'managerHalf',label:'Yarim maosh','type':'number'}],'O‘qituvchi darajalari':[{key:'teacherGrade',label:'Daraja nomi'},{key:'teacherFull',label:'To‘liq maosh','type':'number'}]},
'app-settings':{'Kontent':[{key:'showStories',label:'Stories ko‘rsatish',type:'switch'},{key:'showNews',label:'Yangiliklar ko‘rsatish',type:'switch'}],'Xodimlar':[{key:'faceId',label:'Face ID davomat',type:'switch'},{key:'geolocation',label:'Geolokatsiya orqali davomat',type:'switch'}],'O‘quvchilar':[{key:'archivedAccess',label:'Arxiv o‘quvchiga kirish',type:'switch'},{key:'showBalance',label:'Balansni ko‘rsatish',type:'switch'},{key:'profileEdit',label:'Profil tahrirlash',type:'switch'}]}
};
export const integrations=[['To‘lov tizimlari','Click','Payme','Payze','Uzum','Multicard','Atmos'],['SMS provayderlar','Playmobile','Eskiz','OsonSMS'],['Aloqa va sotuv','Telegram','Kommo','Google Sheets','OnlinePBX','Moizvonki'],['Boshqa','Hikvision','External API','AI / MCP']];
