const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
module.exports=async({pg,base})=>{
 const center=randomUUID(),owner=randomUUID(),cashier=randomUUID(),role=randomUUID();
 await pg.query("INSERT INTO centers(id,name,subdomain,status,tariff) VALUES($1,'Finance QA','finance-qa','Active','Start')",[center]);
 for(const [id,r]of [[owner,'director'],[cashier,'cashier']])await pg.query("INSERT INTO center_users(id,center_id,full_name,email,password_hash,role,status) VALUES($1,$2,$3,$4,'not-a-login-hash',$3,'active')",[id,center,r,r+'@finance.test']);
 const token=id=>require('../middleware/center-auth').signCenterToken({id,center_id:center,role:id===owner?'director':'cashier'},{subdomain:'finance-qa'});
 const call=async(id,body,path='records')=>{const r=await fetch(base+'/api/crm/'+path,{method:body?'POST':'GET',headers:{Host:'finance-qa.eduka.uz','X-Forwarded-Host':'finance-qa.eduka.uz',Origin:'https://finance-qa.eduka.uz',Cookie:'eduka_session='+token(id),'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json()}};
 const create=async(entity,data)=>{const r=await call(owner,{entity,action:'create',data});assert.equal(r.status,200,JSON.stringify(r));return r.body.record};
 const student=await create('students',{name:'Finance learner',phone:'+998901111777'}),cash=await create('cash',{name:'QA cash'});
 const incoming={name:'Payment',student:student.id,cash:cash.id,amount:10.25,date:'2026-10-01',direction:'Kirim',paymentMethod:'Naqd'};
 const accepted=await call(cashier,{entity:'transactions',action:'create',data:incoming});assert.equal(accepted.status,200,JSON.stringify(accepted));
 assert.equal((await call(cashier,{entity:'transactions',action:'create',data:{...incoming,direction:'Chiqim'}})).status,403);
 assert.equal((await call(cashier,{entity:'transactions',action:'create',data:{...incoming,student:''}})).status,403);
 for(const action of ['update','archive'])assert.equal((await call(cashier,{entity:'transactions',action,id:accepted.body.record.id,version:1,data:{...incoming,amount:99}})).status,403);
 assert.equal((await call(cashier,{employee:cashier,month:'2026-10'},'payroll-run')).status,403);
 assert.equal((await call(cashier,undefined,'staff-access')).status,403);
 assert.equal((await call(cashier,undefined,'payroll-preview?month=2026-10')).status,403);
 await pg.query("INSERT INTO eduka_records(id,center_id,entity,data) VALUES($1,$2,'roles',$3)",[role,center,JSON.stringify({name:'Temporary collector','permission:finance:Ko‘rish':true,'permission:finance:Qo‘shish':true})]);
 await pg.query('UPDATE center_users SET role=$2 WHERE id=$1',[cashier,role]);
 await pg.query("INSERT INTO center_settings(center_id,key,value) VALUES($1,'rbac.roles.v1',$2)",[center,JSON.stringify([{id:role,permissions:['finance.*']}])]);
 assert.equal((await call(cashier,{entity:'transactions',action:'create',data:incoming})).status,200);
 await pg.query('UPDATE eduka_records SET deleted=1 WHERE id=$1',[role]);
 assert.equal((await call(cashier,{entity:'transactions',action:'create',data:incoming})).status,403,'archived role cannot fall back to cached privileges');
 const {calculatePayroll}=require('../utils/crm-operations');
 const rows=[{id:'g',entity:'groups',data:{teacher:'t'}},...Array.from({length:3},(_,i)=>({entity:'transactions',data:{student:'s',group:'g',date:'2026-10-01',direction:'Kirim',amount:0.1}})),{entity:'transactions',data:{student:'s',group:'g',date:'2026-10-01',direction:'Chiqim',amount:0.1}}];
 const result=calculatePayroll(rows,{id:'t',data:{salary:0.1,revenuePercent:50}},'2026-10');assert.equal(result.revenue,0.2);assert.equal(result.percentageAmount,0.1);assert.equal(result.total,0.2);
 assert.throws(()=>calculatePayroll(rows,{id:'t',data:{revenuePercent:101}},'2026-10'));
 const {summarize}=require('../utils/crm-finance');
 const report=summarize([{entity:'transactions',data:{direction:'Kirim',amount:999}},{entity:'transactions',data:{direction:'Unknown',amount:999,date:'2026-10-01'}},{entity:'transactions',data:incoming}], '2026-10-01','2026-10-31');assert.equal(report.totals.income,10.25);assert.equal(report.totals.expenses,0);assert.equal(report.undatedCount,1);assert.equal(report.unclassifiedCount,1);
 console.log('PASS: cashier collection boundaries, archived-role revocation, exact payroll decimals and dated finance reports.');
};
