const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
module.exports=async function({pg,base}){
 const center=randomUUID(),other=randomUUID(),user=randomUUID();
 const bcrypt=require('bcryptjs');
 await pg.query("INSERT INTO centers(id,name,subdomain,status,tariff,monthly_payment,next_payment_date) VALUES($1,'Payme QA','payme-qa','Active','Start',123456.78,NOW()+INTERVAL '5 days'),($2,'Other QA','payme-other','Active','Start',123456.78,NULL)",[center,other]);
 await pg.query("INSERT INTO center_users(id,center_id,full_name,email,password_hash,role,status) VALUES($1,$2,'Owner','payme-qa@example.test',$3,'director','active')",[user,center,await bcrypt.hash('local-test-only',4)]);
 const token=require('../middleware/center-auth').signCenterToken({id:user,center_id:center,role:'director'},{subdomain:'payme-qa'});
 const headers={Host:'payme-qa.eduka.uz','X-Forwarded-Host':'payme-qa.eduka.uz',Cookie:'eduka_session='+token,'Content-Type':'application/json',Origin:'https://payme-qa.eduka.uz'};
 const api=async(path,body)=>{const r=await fetch(base+'/api/crm/subscription'+path,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json()}};
 const rpc=async(method,params,key='test-only-key')=>{const r=await fetch(base+'/api/payme',{method:'POST',headers:{'Content-Type':'text/json',Authorization:'Basic '+Buffer.from('Paycom:'+key).toString('base64')},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})});assert.equal(r.status,200);return r.json()};
 const savedEnv={};for(const k of ['PAYME_MERCHANT_ID','PAYME_TEST_KEY','PAYME_KEY','PAYME_MODE','PAYME_LIVE_ENABLED'])savedEnv[k]=process.env[k];
 Object.assign(process.env,{PAYME_MERCHANT_ID:'aaaaaaaaaaaaaaaaaaaaaaaa',PAYME_TEST_KEY:'test-only-key',PAYME_KEY:'live-only-key',PAYME_MODE:'test',PAYME_LIVE_ENABLED:'false'});
 try{
 const key=randomUUID(),one=await api('/checkout',{requestId:key});assert.equal(one.status,200,JSON.stringify(one));const order=one.body;
 assert.equal(order.amount,123456.78);assert.equal(order.mode,'test');assert.equal((await api('/checkout',{requestId:key})).body.id,order.id);assert.equal((await api('/checkout',{requestId:randomUUID()})).body.id,order.id);
 assert.ok(order.checkoutUrl.startsWith('https://test.paycom.uz/'));const decoded=Buffer.from(order.checkoutUrl.split('/').at(-1),'base64').toString();assert.ok(decoded.includes('a=12345678'));assert.ok(decoded.includes('ac.order_id='+order.id));assert.ok(!decoded.includes('key'));
 const p={id:'100000000000000000000001',time:Date.now(),amount:12345678,account:{order_id:order.id}};
 assert.equal((await rpc('CheckPerformTransaction',p,'wrong')).error.code,-32504);
 assert.equal((await rpc('CheckPerformTransaction',{...p,amount:1})).error.code,-31001);
 assert.equal((await rpc('CheckPerformTransaction',{...p,account:{order_id:randomUUID()}})).error.code,-31050);
 assert.equal((await rpc('CheckPerformTransaction',p,'live-only-key')).error.code,-31050,'test invoice rejected by live key');
 assert.equal((await rpc('CheckPerformTransaction',p)).result.allow,true);
 const first=await rpc('CreateTransaction',p);assert.equal(first.result?.state,1,JSON.stringify(first));assert.deepEqual((await rpc('CreateTransaction',p)).result,first.result);
 assert.equal((await rpc('CreateTransaction',{...p,id:'100000000000000000000002'})).error.code,-31050);
 const before=(await pg.query('SELECT next_payment_date FROM centers WHERE id=$1',[center])).rows[0].next_payment_date;
 const done=await rpc('PerformTransaction',{id:p.id});assert.equal(done.result.state,2);assert.deepEqual((await rpc('PerformTransaction',{id:p.id})).result,done.result);
 assert.equal(String((await pg.query('SELECT next_payment_date FROM centers WHERE id=$1',[center])).rows[0].next_payment_date),String(before),'test never extends real subscription');
 assert.equal((await pg.query('SELECT COUNT(*)::int n FROM platform_payments WHERE center_id=$1',[center])).rows[0].n,0);
 assert.equal((await api('/orders/'+order.id)).body.status,'paid');
 const statement=(await rpc('GetStatement',{from:p.time,to:p.time})).result.transactions;assert.equal(statement.length,1);assert.equal(statement[0].account.order_id,order.id);
 const cancelled=await rpc('CancelTransaction',{id:p.id,reason:1});assert.equal(cancelled.result.state,-2);assert.deepEqual((await rpc('CancelTransaction',{id:p.id,reason:1})).result,cancelled.result);
 assert.equal((await rpc('PerformTransaction',{id:p.id})).error.code,-31008);
 const second=(await api('/checkout',{requestId:randomUUID()})).body;
 const p2={...p,id:'100000000000000000000003',time:Date.now(),account:{order_id:second.id}};
 assert.equal((await rpc('CreateTransaction',p2)).result.state,1);
 await pg.query('UPDATE eduka_payme_transactions SET payme_time=$2 WHERE payme_id=$1',[p2.id,Date.now()-43200001]);
 assert.equal((await rpc('PerformTransaction',{id:p2.id})).error.code,-31008);
 const expired=(await rpc('CheckTransaction',{id:p2.id})).result;assert.equal(expired.state,-1);assert.equal(expired.reason,4);
 process.env.PAYME_MODE='live';assert.equal((await api('/checkout',{requestId:randomUUID()})).status,503);process.env.PAYME_LIVE_ENABLED='true';
 const live=(await api('/checkout',{requestId:randomUUID()})).body;assert.ok(live.checkoutUrl.startsWith('https://checkout.paycom.uz/'));
 const lp={...p,id:'200000000000000000000001',time:Date.now(),account:{order_id:live.id}};
 assert.equal((await rpc('CreateTransaction',lp,'live-only-key')).result.state,1);
 assert.equal((await rpc('PerformTransaction',{id:lp.id},'live-only-key')).result.state,2);
 const after=(await pg.query('SELECT next_payment_date FROM centers WHERE id=$1',[center])).rows[0].next_payment_date;assert.equal(new Date(after)-new Date(before),30*86400000);
 await rpc('PerformTransaction',{id:lp.id},'live-only-key');assert.equal((await pg.query('SELECT COUNT(*)::int n FROM platform_payments WHERE center_id=$1',[center])).rows[0].n,1);
 const receipt={status_code:0,qr_code_url:'https://example.test/receipt',fiscal_sign:'test'};
 assert.equal((await rpc('SetFiscalData',{id:lp.id,type:'PERFORM',fiscal_data:receipt},'live-only-key')).result.success,true);
 assert.equal((await api('/orders/'+live.id)).body.receiptUrl,receipt.qr_code_url);
 assert.equal((await rpc('CancelTransaction',{id:lp.id,reason:1},'live-only-key')).result.state,-2);
 assert.equal(String((await pg.query('SELECT next_payment_date FROM centers WHERE id=$1',[center])).rows[0].next_payment_date),String(before));
 assert.equal((await pg.query('SELECT status FROM platform_payments WHERE center_id=$1',[center])).rows[0].status,'Bekor qilindi');
 const alien=(await pg.query("INSERT INTO eduka_subscription_orders(center_id,mode,request_id,tariff,amount) VALUES($1,'live',$2,'Start',100) RETURNING id",[other,randomUUID()])).rows[0];assert.equal((await api('/orders/'+alien.id)).status,404);
 await pg.query("UPDATE centers SET status='Expired' WHERE id=$1",[center]);assert.equal((await api('')).status,200);assert.equal((await api('/checkout',{requestId:randomUUID()})).status,200);
 const locked=await fetch(base+'/api/crm/records',{headers});assert.equal(locked.status,403,'expired access restricted to billing');
 const malformed=await fetch(base+'/api/payme',{method:'POST',headers:{'Content-Type':'text/json'},body:'{'});assert.equal(malformed.status,200);assert.equal((await malformed.json()).error.code,-32700);
 assert.equal((await rpc('MadeUp',{})).error.code,-32601);
 console.log('PASS: Payme auth, invoice prices, retries, timeout persistence, test/live isolation, statements, fiscal data, renewal, refunds and expired-center billing.');
 }finally{for(const [k,v]of Object.entries(savedEnv))v===undefined?delete process.env[k]:process.env[k]=v}
};
