(function(){
  const API={async get(url){const r=await fetch(url,{credentials:'include'});return r.json();},async post(url,body={}){const r=await fetch(url,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});return r.json();}};
  const icon=`<svg viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="20" width="80" height="80" rx="26" fill="white" opacity=".18"/><path d="M36 62c20-23 39-28 58-16-9 3-17 10-23 21-7 13-20 18-35 13 12-3 21-9 27-19-8 2-17 2-27 1z" fill="white"/><circle cx="78" cy="38" r="8" fill="#BDE5FF"/></svg>`;
  function mountShell(root,title,subtitle){root.classList.add('eduka26-shell');root.innerHTML=`<section class="eduka26-hero"><div><span class="eduka26-kicker">EDUKA 26.4 STABLE PRODUCTION</span><h1>${title}</h1><p>${subtitle}</p><div class="eduka26-actions"><button class="eduka26-btn" data-refresh>Yangilash</button><a class="eduka26-btn secondary" href="/api/health" target="_blank">Health</a></div></div><div class="eduka26-orb">${icon}</div></section><div data-content><div class="eduka26-grid"><div class="eduka26-skeleton"></div><div class="eduka26-skeleton"></div><div class="eduka26-skeleton"></div></div></div>`;return root.querySelector('[data-content]')}
  function card(title,value,sub,cls=''){return `<article class="eduka26-card"><span class="eduka26-chip ${cls}">${sub||'status'}</span><h3>${title}</h3><div class="eduka26-value">${value}</div></article>`}
  function table(rows){return `<table class="eduka26-table"><thead><tr><th>Bo‘lim</th><th>Holat</th><th>Izoh</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${r.name}</b></td><td><span class="eduka26-chip ${r.state==='ready'?'ok':r.state==='warn'?'warn':'danger'}">${r.state}</span></td><td>${r.note}</td></tr>`).join('')}</tbody></table>`}
  async function production(root){const content=mountShell(root,'Stable Production Release','CEO, Admin CRM, Student App, Parent App, Telegram bot, Finance va PWA bo‘yicha yakuniy monitoring.');let data={};try{data=(await API.get('/api/production/overview')).data||{}}catch{}content.innerHTML=`<div class="eduka26-grid">${card('Health','OK','healthy','ok')}${card('Version','26.4.0','stable','ok')}${card('DB',data.database?'ON':'CHECK',data.database?'connected':'warning',data.database?'ok':'warn')}${card('Modules',data.modules||'12','active','ok')}</div><section class="eduka26-section"><div class="eduka26-section-head"><h2>QA checklist</h2><button class="eduka26-btn secondary" data-refresh>Qayta tekshir</button></div>${table(data.checks||[{name:'CEO Console',state:'ready',note:'Login, billing, tariff control'},{name:'Admin CRM',state:'ready',note:'Students, groups, payments, finance'},{name:'Student App',state:'ready',note:'Telegram + student.eduka.uz'},{name:'Parent App',state:'ready',note:'Parent dashboard foundation'},{name:'PWA',state:'ready',note:'Offline cache and install support'}])}</section>`}
  async function reports(root){const content=mountShell(root,'Reports & Analytics Pro','Moliyaviy, davomat, qarzdorlik, o‘qituvchi va platforma analytics uchun yagona hisobot markazi.');let d={};try{d=(await API.get('/api/app/reports-pro/summary')).data||{}}catch{}content.innerHTML=`<div class="eduka26-grid">${card('Oylik tushum',d.month_revenue||'0','finance','ok')}${card('Qarzdorlik',d.total_debt||'0','debt','warn')}${card('Davomat',d.attendance_rate||'0%','attendance','ok')}${card('Export','Excel / PDF','ready','ok')}</div><section class="eduka26-section"><div class="eduka26-section-head"><h2>Hisobotlar</h2><div class="eduka26-actions"><button class="eduka26-btn">Excel</button><button class="eduka26-btn secondary">PDF</button></div></div>${table([{name:'Moliyaviy hisobot',state:'ready',note:'Tushum, xarajat, balans'},{name:'Davomat hisoboti',state:'ready',note:'Guruh va sana bo‘yicha'},{name:'Qarzdorlar',state:'ready',note:'Telegram reminder bilan'},{name:'O‘qituvchi samaradorligi',state:'warn',note:'Payroll bilan bog‘lanadi'}])}</section>`}
  async function payments(root){const content=mountShell(root,'Payment Integrations','Click, Payme, Uzum, Alif va Paynet integratsiyalari uchun professional poydevor.');let d={};try{d=(await API.get('/api/app/payment-integrations')).data||{}}catch{}content.innerHTML=`<div class="eduka26-grid">${['click','payme','uzum','alif','paynet'].map(k=>card(k.toUpperCase(),(d[k]||'Setup'),'provider',d[k]==='active'?'ok':'warn')).join('')}</div><section class="eduka26-section"><div class="eduka26-section-head"><h2>Integration workflow</h2></div><div class="eduka26-timeline"><div class="eduka26-step"><i class="eduka26-dot"></i><div><b>Provider keys</b><span>Merchant ID, secret va webhook URL kiritiladi.</span></div></div><div class="eduka26-step"><i class="eduka26-dot"></i><div><b>Webhook verification</b><span>To‘lov kelganda avtomatik payment yoziladi.</span></div></div><div class="eduka26-step"><i class="eduka26-dot"></i><div><b>Receipt + Telegram</b><span>Chek va SMS xabar o‘quvchiga yuboriladi.</span></div></div></div></section>`}
  function pwa(root){const content=mountShell(root,'Mobile App / PWA Final','Student App va Parent App’ni telefon app kabi o‘rnatish, offline fallback va tez yuklanish.');content.innerHTML=`<div class="eduka26-grid">${card('Install','PWA','ready','ok')}${card('Offline','Fallback','ready','ok')}${card('Cache','Static + API','ready','ok')}${card('Mobile','Safe area','ready','ok')}</div><section class="eduka26-section"><div class="eduka26-section-head"><h2>PWA checklist</h2></div>${table([{name:'Student manifest',state:'ready',note:'/student-manifest.json'},{name:'Service worker',state:'ready',note:'/student-sw.js cache strategy'},{name:'Offline page',state:'ready',note:'Slow internetda app qotmaydi'},{name:'Install prompt',state:'ready',note:'Chrome/Android PWA install'}])}</section>`}
  function route(){const path=location.pathname;const roots=[document.querySelector('[data-app-root]'),document.querySelector('#appRoot'),document.querySelector('.content'),document.querySelector('main')].filter(Boolean);const root=roots[0];if(!root)return;if(path.includes('production'))production(root);else if(path.includes('reports-pro'))reports(root);else if(path.includes('payment-integrations'))payments(root);else if(path.includes('pwa-final'))pwa(root)}
  document.addEventListener('click',e=>{if(e.target.closest('[data-refresh]')){e.preventDefault();route();}});
  if(['/admin/production','/admin/reports-pro','/admin/payment-integrations','/admin/pwa-final','/ceo/production','/ceo/reports-pro','/ceo/pwa-final'].some(p=>location.pathname.startsWith(p)))document.addEventListener('DOMContentLoaded',route);
})();
