const EDUKA_STUDENT_VERSION = "22.1.1";
const screen = document.querySelector("[data-student-screen]");
const logo = "/assets/logo_icon.webp";
const state = { token: "", data: null, route: "home", loginStep: "phone", phone: "", org: null, toastTimer: null };

function $(sel, root = document) { return root.querySelector(sel); }
function esc(v) { return String(v ?? "").replace(/[&<>"']/g, (m) => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m])); }
function n(v) { return Number(v || 0).toLocaleString("uz-UZ"); }
function money(v) { return `${n(v)} so'm`; }
function date(v) { if (!v) return "-"; const d = new Date(v); return Number.isNaN(d.getTime()) ? String(v).slice(0, 10) : d.toLocaleDateString("uz-UZ"); }
function firstName(name) { return String(name || "O'quvchi").trim().split(/\s+/)[0] || "O'quvchi"; }
function initials(name) { return String(name || "O").trim().split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase(); }
function setToken(t) { state.token = t || ""; if (t) localStorage.setItem("eduka_student_token", t); }
function getToken() { const p = new URLSearchParams(location.search); return p.get("token") || localStorage.getItem("eduka_student_token") || ""; }
function route() { const parts = location.pathname.replace(/\/+$/, "").split("/").filter(Boolean); return parts[1] || "home"; }
function go(r) { history.pushState({}, "", `/app/${r}`); renderRoute(r); }
function toast(msg) { clearTimeout(state.toastTimer); const old = $(".toast"); old?.remove(); const el = document.createElement("div"); el.className = "toast"; el.textContent = msg; document.body.append(el); state.toastTimer = setTimeout(()=>el.remove(), 3200); }
async function api(path, opts = {}) { const headers = { "Content-Type":"application/json", ...(opts.headers || {}) }; if (state.token) headers.Authorization = `Bearer ${state.token}`; const res = await fetch(path, { ...opts, headers }); const text = await res.text(); let data={}; try { data=JSON.parse(text); } catch { data={ ok:false, message:text || "Server javob bermadi" }; } if (!res.ok || data.ok === false) throw new Error(data.message || "Xatolik yuz berdi"); return data; }
function enabled(key) { return !state.data?.enabled || state.data.enabled[key] !== false; }
function nav(active) { const items = [["home","Bosh sahifa","⌂"],["schedule","Jadval","▣"],["payments","To'lov","▣"],["attendance","Davomat","◉"],["profile","Profil","○"]]; return `<nav class="bottom-nav">${items.map(([k,l,i]) => `<button class="${active===k?'active':''}" data-go="${k}"><span>${i}</span>${l}</button>`).join("")}</nav>`; }
function bindNav(root = screen) { root.querySelectorAll("[data-go]").forEach(b => b.onclick = () => go(b.dataset.go)); }

async function boot() {
  setToken(getToken());
  document.body.classList.remove("is-booting");
  document.querySelector("[data-boot-loader]")?.remove();
  if (window.Telegram?.WebApp) { Telegram.WebApp.ready(); Telegram.WebApp.expand(); }
  if (state.token) {
    try { await load(); renderRoute(route()); return; } catch { localStorage.removeItem("eduka_student_token"); state.token=""; }
  }
  renderSplash();
}
async function load() { state.data = await api("/api/student-app/me"); return state.data; }

function renderSplash() { screen.innerHTML = `<section class="app-splash"><img class="logo-main" src="${logo}" alt="Eduka"/><h1>EDUKA</h1><p>Bilim bilan kelajakni<br/>birga quramiz!</p><button class="secondary full" data-start>Boshlash →</button></section>`; $('[data-start]').onclick=()=>renderLogin(); }
function renderLogin(message="") { screen.innerHTML = `<section class="login-wrap"><div class="login-card"><img class="logo-small" src="${logo}" alt="Eduka"/><h1>EDUKA</h1><p class="muted">Student App</p>${message?`<div class="pill red">${esc(message)}</div>`:""}<form data-login><label class="field"><span>☎</span><input name="phone" placeholder="Telefon raqami yoki ID" value="${esc(state.phone)}" required /></label><label class="field"><span>🔒</span><input name="password" type="password" placeholder="Parol" required /></label><button class="primary full">Kirish</button><button type="button" class="mini-link">Parolni unutdingizmi?</button></form></div></section>`; const form=$('[data-login]'); form.onsubmit=async(e)=>{e.preventDefault(); const fd=new FormData(form); state.phone=String(fd.get('phone')||''); try{const out=await api('/api/student-app/auth/password',{method:'POST',body:JSON.stringify({phone:state.phone,password:String(fd.get('password')||''), telegram_user_id: window.Telegram?.WebApp?.initDataUnsafe?.user?.id || null, telegram_chat_id: window.Telegram?.WebApp?.initDataUnsafe?.user?.id || null})}); setToken(out.token); await load(); go('home');}catch(err){renderLogin(err.message)}}; }

function header() { const s=state.data?.student||{}; return `<div class="topbar"><div class="hello"><div class="avatar">${s.avatarUrl?`<img src="${esc(s.avatarUrl)}"/>`:esc(initials(s.fullName))}</div><div><h2>Salom, ${esc(firstName(s.fullName))}! 👋</h2><p>Bugun zo'r kun bo'lsin!</p></div></div><button class="icon-btn" data-go="notifications">🔔</button></div>`; }
function home() { const d=state.data, s=d.student||{}, lesson=d.lessons?.[0]||{}, ps=d.paymentSummary||{}; screen.innerHTML = `${header()}<div class="grid-2"><article class="card"><h3>Bugungi dars</h3><b>${esc(lesson.time||'Dars yo‘q')}</b><small>${esc(lesson.title||lesson.group_name||'Jadval hali kiritilmagan')}</small></article><article class="card green-card"><h3>To'lov holati</h3><b>${Number(ps.balance||0)>0?money(ps.balance):'To‘langan'}</b><small>${Number(ps.balance||0)>0?'Qarzdorlik mavjud':'Qarz yo‘q'}</small></article><article class="card"><h3>Davomat</h3><b>${n(s.attendancePercent||0)}%</b><small>Umumiy ko'rsatkich</small></article><article class="card"><h3>Keyingi dars</h3><b>${esc(d.lessons?.[1]?.time || lesson.time || '-')}</b><small>${esc(d.lessons?.[1]?.title || lesson.title || 'Dars topilmadi')}</small></article></div>${enabled('coins')?`<article class="card coin-card" style="margin-top:12px"><div class="coin-row"><span class="coin">S</span><div><h3>Coin balans</h3><strong>${n(s.coins||0)}</strong></div><button class="ghost" data-go="rewards">Mukofotlar 🎁</button></div></article>`:''}<div class="section-title"><h2>Bildirishnomalar</h2><button class="mini-link" data-go="notifications">Barchasi</button></div><div class="list">${(d.notifications||[]).slice(0,3).map(item=>row(item.title,item.description,item.type==='coin'?'+':'')).join('') || empty('Hozircha xabar yo‘q')}</div>${nav('home')}`; bindNav(); }
function row(title, sub='', right='') { return `<div class="row"><div><b>${esc(title)}</b><small>${esc(sub)}</small></div>${right?`<span class="pill">${esc(right)}</span>`:''}</div>`; }
function empty(t) { return `<div class="empty">${esc(t)}</div>`; }

function schedule() { const days=['Du','Se','Ch','Pa','Ju','Sh','Ya']; const lessons=state.data?.lessons||[]; screen.innerHTML=`<div class="topbar"><h2>Jadval</h2><button class="icon-btn" data-go="home">⌂</button></div><div class="tabs"><button class="active">Hafta</button><button>Kun</button></div><div class="calendar">${days.map((x,i)=>`<div class="day ${i===1?'active':''}">${x}<br/>${20+i}</div>`).join('')}</div><div class="section-title"><h2>Bugungi darslar</h2></div><div class="list">${lessons.map((l,i)=>`<div class="row ${i===0?'highlight':''}"><div class="schedule-row"><span class="time">${esc(l.time)}</span><div><b>${esc(l.title||l.group_name)}</b><small>${esc(l.group_name||'')} • ${esc(l.teacher_name||'-')} • ${esc(l.room||'-')}</small></div></div></div>`).join('')||empty('Jadval hali kiritilmagan')}</div>${nav('schedule')}`; bindNav(); }
function payments() { const d=state.data, ps=d.paymentSummary||{}, payments=d.payments||[]; screen.innerHTML=`<div class="topbar"><h2>To'lovlar</h2><button class="icon-btn" data-go="home">⌂</button></div><article class="card blue-card"><h3>Joriy balans</h3><strong>${money(ps.balance||0)}</strong><small>${Number(ps.balance||0)>0?'Qarzdorlik mavjud':'Qarz yo‘q'}</small></article>${state.data?.settings?.online_payment_enabled?`<button class="primary full" style="margin:12px 0">To'lov qilish</button>`:''}<div class="grid-2" style="margin-top:12px"><article class="card"><h3>Jami to'langan</h3><b>${money(ps.paid||0)}</b></article><article class="card"><h3>To'lanishi kerak</h3><b>${money(ps.due||0)}</b></article></div><div class="section-title"><h2>To'lov tarixi</h2></div><div class="list">${payments.map(p=>row(date(p.paid_at||p.payment_date), `${p.payment_type||'To‘lov'} • ${money(p.amount||0)}`, p.status||'paid')).join('')||empty('To‘lovlar topilmadi')}</div>${nav('payments')}`; bindNav(); }
function attendance() { const s=state.data?.student||{}, records=state.data?.attendance||[]; const pct=s.attendancePercent||0; screen.innerHTML=`<div class="topbar"><h2>Davomat</h2><button class="icon-btn" data-go="home">⌂</button></div><article class="card"><div class="progress-ring" style="background:conic-gradient(var(--green) 0 ${pct*3.6}deg,#e5eef8 ${pct*3.6}deg)"><span>${pct}%</span></div><p class="muted" style="text-align:center">Umumiy davomat</p></article><div class="section-title"><h2>May 2024</h2></div><div class="calendar">${Array.from({length:31},(_,i)=>`<div class="day ${[7,14,21,28].includes(i+1)?'active':''}">${i+1}</div>`).join('')}</div><div class="section-title"><h2>So'nggi darslar</h2></div><div class="list">${records.slice(0,8).map(r=>row(date(r.lesson_date), r.note||'Dars', r.status||'present')).join('')||empty('Davomat yozuvlari yo‘q')}</div>${nav('attendance')}`; bindNav(); }
function profile() { const s=state.data?.student||{}, o=state.data?.organization||{}; screen.innerHTML=`<section class="profile-head"><div class="avatar">${s.avatarUrl?`<img src="${esc(s.avatarUrl)}"/>`:esc(initials(s.fullName))}</div><h2>${esc(s.fullName)}</h2><p>ID: ${esc(s.id)}</p></section><div class="info-list">${row('Telefon',s.phone||'-')}${row('Ota-ona telefoni',s.parentPhone||'-')}${row('Kurs',s.courseName||'-')}${row('Guruh',s.groupName||'-')}${row('O‘quv markaz',o.name||'Eduka')}</div><button class="primary full" style="margin-top:14px" data-edit-profile>Profilni tahrirlash</button><button class="secondary full" style="margin-top:10px" data-change-pass>Parolni almashtirish</button><button class="ghost full" style="margin-top:10px" data-logout>Chiqish</button>${nav('profile')}`; bindNav(); $('[data-logout]').onclick=async()=>{try{await api('/api/student-app/auth/logout',{method:'POST'});}catch{} localStorage.removeItem('eduka_student_token'); setToken(''); renderLogin();}; $('[data-edit-profile]').onclick=()=>editProfile(); $('[data-change-pass]').onclick=()=>changePassword(); }
function coins() { const s=state.data?.student||{}, items=state.data?.coinTransactions||[]; screen.innerHTML=`<div class="topbar"><h2>Coinlar</h2><button class="icon-btn" data-go="home">⌂</button></div><article class="card blue-card"><h3>Umumiy balans</h3><strong>🪙 ${n(s.coins||0)}</strong><button class="secondary full" data-go="rewards">Sovg'alar do'koniga o'tish →</button></article><div class="section-title"><h2>So'nggi faoliyat</h2></div><div class="list">${items.map(i=>row(i.teacher_name||'Ustoz',i.reason||'Coin berildi',`${Number(i.amount)>0?'+':''}${i.amount}`)).join('')||empty('Coin tarixi yo‘q')}</div>${nav('profile')}`; bindNav(); }
function rewards() { const s=state.data?.student||{}, items=state.data?.rewards||[]; screen.innerHTML=`<div class="topbar"><h2>Sovg'alar do'koni</h2><span class="pill">🪙 ${n(s.coins||0)}</span></div><div class="reward-grid">${items.map(x=>`<article class="card reward"><div class="pic">${x.image_url?`<img src="${esc(x.image_url)}" style="max-width:100%;max-height:80px"/>`:'🎁'}</div><b>${esc(x.title)}</b><small>${esc(x.description||'')}</small><p><span class="coin">S</span> ${n(x.coin_price)}</p><button class="primary full" data-redeem="${x.id}">Olish</button></article>`).join('')||empty('Sovg‘alar hali qo‘shilmagan')}</div>${nav('profile')}`; bindNav(); screen.querySelectorAll('[data-redeem]').forEach(btn=>btn.onclick=async()=>{try{await api(`/api/student-app/rewards/${btn.dataset.redeem}/redeem`,{method:'POST',body:'{}'}); toast('Sovg‘a so‘rovi yuborildi'); await load(); rewards();}catch(e){toast(e.message)}}); }
function ranking() { const list=state.data?.ranking||[]; screen.innerHTML=`<div class="topbar"><h2>Reyting</h2><button class="icon-btn" data-go="home">⌂</button></div><div class="leader-top">${list.slice(0,3).map((x,i)=>`<article class="card leader ${i===0?'main':''}"><div class="avatar">${esc(initials(x.full_name))}</div><b>${esc(x.full_name)}</b><small>🪙 ${n(x.score)}</small></article>`).join('')}</div><div class="section-title"><h2>Top o‘quvchilar</h2></div><div class="list">${list.map((x,i)=>row(`${i+1}. ${x.full_name}`, 'Coin reyting', `🪙 ${n(x.score)}`)).join('')||empty('Reyting yo‘q')}</div>${nav('profile')}`; bindNav(); }
function achievements() { const items=state.data?.achievements||[]; screen.innerHTML=`<div class="topbar"><h2>Yutuqlar</h2><button class="icon-btn" data-go="home">⌂</button></div><div class="badge-grid">${items.map(x=>`<article class="card badge"><div class="medal">${x.completed?'🏆':'⭐'}</div><b>${esc(x.title)}</b><small>${esc(x.description||'')}</small><p>${n(x.progress)}/${n(x.target)}</p></article>`).join('')||empty('Yutuqlar hali yo‘q')}</div>${nav('profile')}`; bindNav(); }
function notifications() { const items=state.data?.notifications||[]; screen.innerHTML=`<div class="topbar"><h2>Bildirishnomalar</h2><button class="icon-btn" data-go="home">⌂</button></div><div class="tabs"><button class="active">Barchasi</button><button>Dars</button><button>To'lov</button><button>Coin</button></div><div class="list">${items.map(i=>row(i.title,i.description,date(i.time))).join('')||empty('Xabarlar yo‘q')}</div>${nav('home')}`; bindNav(); }
function materials() { const items=state.data?.materials||state.data?.library||[]; screen.innerHTML=`<div class="topbar"><h2>Materiallar</h2><button class="icon-btn" data-go="home">⌂</button></div><div class="tabs"><button class="active">Barchasi</button><button>PDF</button><button>Video</button></div><div class="list">${items.map(i=>row(i.title||'Material',`${i.type||'PDF'} • ${i.level||''}`, i.file_url?'⬇':'›')).join('')||empty('Materiallar hali qo‘shilmagan')}</div>${nav('profile')}`; bindNav(); }
function editProfile(){const s=state.data?.student||{}; screen.insertAdjacentHTML('beforeend',`<div class="drawer"><div class="drawer-head"><h2>Profilni tahrirlash</h2><button class="icon-btn" data-close>×</button></div><form data-profile><label>FISH<input name="full_name" value="${esc(s.fullName)}"/></label><label>Telefon<input name="phone" value="${esc(s.phone||'')}"/></label><label>Ota-ona telefoni<input name="parent_phone" value="${esc(s.parentPhone||'')}"/></label><label>Manzil<textarea name="address">${esc(s.address||'')}</textarea></label><label>Email<input name="email" value="${esc(s.email||'')}"/></label><button class="primary full">Saqlash</button></form></div>`); $('[data-close]').onclick=()=>$('.drawer').remove(); $('[data-profile]').onsubmit=async(e)=>{e.preventDefault(); const data=Object.fromEntries(new FormData(e.target)); try{await api('/api/student-app/profile',{method:'POST',body:JSON.stringify(data)}); await load(); toast('Profil saqlandi'); profile();}catch(err){toast(err.message)}}}
function changePassword(){screen.insertAdjacentHTML('beforeend',`<div class="drawer"><div class="drawer-head"><h2>Parolni almashtirish</h2><button class="icon-btn" data-close>×</button></div><form data-pass><label>Joriy parol<input type="password" name="current_password"/></label><label>Yangi parol<input type="password" name="new_password" minlength="6" required/></label><button class="primary full">Saqlash</button></form></div>`); $('[data-close]').onclick=()=>$('.drawer').remove(); $('[data-pass]').onsubmit=async(e)=>{e.preventDefault(); try{await api('/api/student-app/password',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))}) ; toast('Parol yangilandi'); $('.drawer')?.remove();}catch(err){toast(err.message)}}}

async function renderRoute(r=route()){ if(!state.data){ try{await load()}catch{return renderLogin()}} state.route=r; const map={home,schedule,payments,attendance,profile,coins,rewards,ranking,achievements,notifications,materials,library:materials,"payment-history":payments}; (map[r]||home)(); }
window.addEventListener('popstate',()=>renderRoute(route()));
boot();
